### PR TITLE
Create new subtasks in parent swimlane

### PR DESCRIPTION
**Pull request by TOSCom-DanielEder**
Referencing [1953](https://github.com/wekan/wekan/issues/1953)
Implements the changes suggested in [1953#issuecomment-604310679](https://github.com/wekan/wekan/issues/1953#issuecomment-604310679)

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2976)

### CODE REVIEW

**Comment by xet7** [comment]
@TOSCom-DanielEder 

Are you planning to do any more changes? Your pull request is still in draft mode, so I can not click "Merge pull request" button.

**Comment by TOSCom-DanielEder** [comment]
> @TOSCom-DanielEder
> 
> Are you planning to do any more changes? Your pull request is still in draft mode, so I can not click "Merge pull request" button.

Sorry for the hold up, we've got a pending confirmation for the CLA, for this change it's naturally not a big deal, but as it applies for all other contributions as well I need to go through the process here.

**Comment by xet7** [comment]
@TOSCom-DanielEder 

Previously some that did think current Wekan CLA would be too broad, I did allow them to use [Apache I-CLA](https://apache.org/licenses/icla.pdf) instead like here https://github.com/wekan/wekan/pull/2287

For some other smaller contributions, not all have signed CLA, so in that case I presume Wekan MIT licence applies. Contributed code will also become MIT licensed.

AFAIK CLA is mainly about that code can be added to Wekan.

As you see from bottom of https://github.com/wekan/wekan most of Wekan is MIT licensed code. There is also some BSD-3-clause and Apache 2.0 code.

@ocdtrekkie Do you have anything to add to this?

**Comment by ocdtrekkie** [comment]
In the case of a minor bugfix-level change, the CLA is pretty irrelevant, but since it'll affect any future contribution they offer up, it seems practical to get it sorted, if their employer has any concerns.

**Comment by TOSCom-DanielEder** [comment]
As discussed in #1953 using the parent lane id directly does not work in scenarios where subtasks are in a separate board. With [89fe030](https://github.com/wekan/wekan/pull/2976/commits/89fe030fa35ea24195ac366aaf3a1c917b305249) the title of the parent card lane is used to look up the target lane in the subtask board. If that lookup fails, the default lane of the target board is used.

**Pull request merged**
