### PR TITLE
Feature: Docker Health Check

### PR DESCRIPTION
**Pull request by luketainton**
Adding health checks to the Docker image so that the container can auto-restart on crash.

### CODE REVIEW

**Comment by mfilser** [comment]
The HEALTHCHECK completly brokes my Docker instance, i always get a error "404 not found".
After removing the HEALTHCHECK command Docker works again.
I doubt it ever worked because the build already failed after this commit.
@xet7 Do you also have problems?
@luketainton Thanks for the contribution, but i think it doesn’t work as expected.

**Comment by luketainton** [comment]
Hmm, apologies. I'll take another look into it.

**Comment by mfilser** [comment]
I removed it for my Installation, but i think the last release will not work.

Does it work for you?

**Comment by luketainton** [comment]
I tried to rebuild the image both WITH and WITHOUT the health check, and it seems to fail around the `meteor build` step:
```
<truncated>
#0 137.8 Downloading Meteor distribution
#0 169.6
#0 169.6 Meteor 2.12 has been installed in your home directory (~/.meteor).
#0 169.6 Writing a launcher script to /usr/local/bin/meteor for your convenience.
#0 169.6
#0 169.6 To get started fast:
#0 169.6
#0 169.6   $ meteor create ~/my_cool_app
#0 169.6   $ cd ~/my_cool_app
#0 169.6   $ meteor
#0 169.6
#0 169.6 Or see the docs at:
#0 169.6
#0 169.6   docs.meteor.com
#0 169.6
#0 169.6 Deploy and host your app with Cloud:
#0 169.6
#0 169.6   www.meteor.com/cloud
#0 169.6
#0 169.6 + mv /root/.meteor /home/wekan/
#0 169.7 + chown wekan --recursive /home/wekan/.meteor
#0 170.5 + sed -i s/api\.versionsFrom/\/\/api.versionsFrom/ /home/wekan/app/packages/meteor-useraccounts-core/package.js
#0 170.5 sed: can't read /home/wekan/app/packages/meteor-useraccounts-core/package.js: No such file or directory
#0 170.5 + cd /home/wekan/app
#0 170.5 + mkdir -p /home/wekan/.npm
#0 170.5 + chown wekan --recursive /home/wekan/.npm /home/wekan/.config /home/wekan/.meteor
#0 171.2 + chmod u+w app.json package-lock.json package.json scalingo.json settings.json
#0 171.2 + gosu wekan:wekan npm install
#0 176.2 npm WARN old lockfile
#0 176.2 npm WARN old lockfile The package-lock.json file was created with an old version of npm,
#0 176.2 npm WARN old lockfile so supplemental metadata must be fetched from the registry.
#0 176.2 npm WARN old lockfile
#0 176.2 npm WARN old lockfile This is a one-time fix-up, please be patient...
#0 176.2 npm WARN old lockfile
#0 257.5 npm WARN deprecated @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
#0 265.8 npm WARN deprecated core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
#0 278.4
#0 278.4 added 507 packages, and audited 614 packages in 2m
#0 278.4
#0 278.4 84 packages are looking for funding
#0 278.4   run `npm fund` for details
#0 278.4
#0 278.4 1 moderate severity vulnerability
#0 278.4
#0 278.4 To address all issues (including breaking changes), run:
#0 278.4   npm audit fix --force
#0 278.4
#0 278.4 Run `npm audit` for details.
#0 278.4 + gosu wekan:wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build
#0 386.2 Killed
```

Am I missing something when trying to build locally?

**Comment by xet7** [comment]
@luketainton 

To build from source and run locally with Docker, you uncomment these lines:
https://github.com/wekan/wekan/blob/master/docker-compose.yml#L143-L145

And run in wekan directory:
```
docker-compose up -d
```

**Comment by xet7** [comment]
I usually build Docker images on Linux, because Linux has much faster filesystem than Windows. WeKan .zip file has aboult 60 000 files of HTML/CSS/JS/images/text.

**Comment by luketainton** [comment]
I'm on a Mac but I'm using a Docker context pointing to a Linux VM to build. I did as you mentioned and I'm getting that error. I might try using the `arm64v8` Dockerfile (this is an Apple Silicon Mac).

**Comment by xet7** [comment]
@luketainton 

I have not tested that `arm64v8` Dockerfile, does it work at all. Previously there was some problems using WeKan on Alpine Linux based Docker images.

**Comment by xet7** [comment]
@luketainton 

Developing WeKan on Mac: https://github.com/wekan/wekan/wiki/Mac

**Comment by xet7** [comment]
Building on macOS works.

Building on Linux arm64 (like Asahi Linux) is not merged yet https://github.com/meteor/meteor/pull/12160#issuecomment-1483260406

My current release scripts modify Linux amd64 bundle content to work on other CPU OS:
https://github.com/wekan/wekan/tree/master/releases

**Comment by luketainton** [comment]
I switched to a completely separate Rocky Linux VM (the previous VM was on my Mac) and building here is working, so I'll use this host for now and work out the Mac problems later :)

**Pull request merged**
