### PR TITLE
Move more global subscription to template subscription

### PR DESCRIPTION
**Pull request by mfshiu**
Move global subscription to template subscription that subscription will stop when template is unused. It's very important for efficiency especially in large number of users.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1373)

### CODE REVIEW

**Comment by mfshiu** [comment]
Merged conflict in boardLists.js

**Comment by xet7** [comment]
@mfshiu 

Could you make new fork of Wekan devel branch, add your changes to that, and make new pull request? This pull request has a lot of old stuff like release v0.53 tag etc.

**Comment by xet7** [comment]
@mfshiu  

I would also recommend fixing npm lint errors before committing etc:
https://github.com/wekan/wekan/wiki/Developer-Documentation#preventing-travis-ci-lint-errors-before-submitting-pull-requests

**Comment by xet7** [comment]
Actually, I think https://github.com/wekan/wekan/pull/1373/commits/03ddd8e9ec13b7098412233988bb4a827c13d15e is the commit that is the main change in this. I'll try to test and merge it manually.

**Comment by xet7** [comment]
I merged this manually at https://github.com/wekan/wekan/commit/233554a3d69f1cf3a509e540fc1623d17c357037 . Thanks!

**Comment by mfshiu** [comment]
OK, Thanks
Next time, I will make new fork of Wekan devel branch.

**Pull request closed without merging**
