### PR TITLE
Submit inline form on click outside

### PR DESCRIPTION
**Pull request by pravdomil**
make sense?

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1717)

### CODE REVIEW

**Comment by zypA13510** [comment]
I think the argument for both behaviors is equally true:
On one hand, I've seen many new users trying to save by clicking outside, so it is reasonable to make clicking outside to save. OTOH, if the user expects it to save, when it is not, the user can always re-enter what they have just entered. But if the user expects it to discard, when it is actually saved, the old data is lost forever and there will be no way to recover. (It is much more likely to remember the new input than the old data)

I think the current behavior in "description" field is fine. It saves the input into a temporary "unsaved description" and asks the user whether they would like to discard it.

**Comment by pravdomil** [comment]
gif

finder macos

**Comment by pravdomil** [comment]
gif

finder mac os

**Comment by zypA13510** [comment]
@pravdomil But I'm pretty sure you can find plenty of web apps these days that do the opposite.
And in the renaming example, you can always undo. But in Wekan you cannot (if it saves when you intended to discard).

**Comment by pravdomil** [comment]
> I think the current behavior in "description" field is fine. It saves the input into a temporary "unsaved description" and asks the user whether they would like to discard it.

this PR is especially for edit `Cart Title` in `Board View` and `Card Detail`

**Pull request merged**
