### PR TITLE
Try to support old Meteor 3.0 syntax of _ensureIndex (not new createI…

### PR DESCRIPTION
**Pull request by SeveriTyo**
…ndex) for Sandstorm.

edited default list width

Thanks to xet7.

### CODE REVIEW

**Comment by mfilser** [comment]
Current release is Meteor 2.12, so why supporting "old" Meteor 3.0 ? 3.0 is the upcoming release, not a old one. 

https://github.com/wekan/wekan/blob/master/.meteor/release

If i remember right the change from `_ensureIndex` to `createIndex` was necessary for Meteor 2.7. I guess this PR will break things again (not tested yet)

**Comment by ocdtrekkie** [comment]
@mfilser Probably meant to say Mongo 3.0, not Meteor.

**Comment by mfilser** [comment]
Hm, maybe.
Mongo 3.0 is so pretty old. And current Meteor needs Mongo 5.

**Comment by xet7** [comment]
@mfilser @ocdtrekkie 

Please ignore, these were jus tests. Actually this was just about list width, but old commits were included also.

**Pull request closed without merging**
