### PR TITLE
Replace CollectionFS with meteor-file-collection

### PR DESCRIPTION
**Pull request by eemeli**
The library currently used by Wekan for attachments (CollectionFS) is not very actively maintained, having been deprecated for most of 2016. It's also somewhat extensive in its feature set, of which Wekan uses only a fraction but is burdened by bugs resulting from said complexity. So I'm here proposing to replace it with [meteor-file-collection](/vsivsi/meteor-file-collection/), which has mostly the same interfaces as CollectionFS and also uses GridFS for storage.

In addition to being simpler and more secure, the built-in [resumable.js](http://resumablejs.com/) integration will enable simultaneous upload of multiple files, as well as drag-and-drop for attachment upload.

The particular CollectionFS bug that I hit that prompted its replacement was its inability to deal well with local uploads, a part of a custom import job that I needed to get to work.

This is a work-in-progress, so should not be merged until the following are all done:
- [x] Basic attachment upload/download/delete support
- [ ] Avatar upload support
- [ ] Drag-and-drop for attachment upload (#300)
- [ ] Upload progress indicator
- [ ] Better fix for opening non-image attachments (#99)
- [ ] Re-enabling attachment import
- [ ] Migration script from CollectionFS

At the moment, using missing features result in console warnings with the prefix `[re-attach]`.

In addition to the above, other issues that would probably get resolved by this include: #142, #386, #544, #698, #784, CollectionFS/Meteor-CollectionFS#449.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/875)

### CODE REVIEW

**Comment by xet7** [comment]
@eemeli

Thanks!

I think this can be merged when it automatically detects CollectionFS attachments and converts them meteor-file-collection. On some platforms like Sandstorm where Wekan code is signed and read-only, it's not possible to run separate migration scripts.

**Comment by GhassenRjab** [comment]
Can other developers join and contribute to this PR? If yes, how?

**Comment by xet7** [comment]
@GhassenRjab 

https://stackoverflow.com/questions/22237609/adding-to-someone-else-s-pull-request-on-a-github-project-that-i-do-not-own

**Comment by eemeli** [comment]
Sorry, looks like I don't have the time I expected to have to work on Wekan stuff. The "Allow edits from maintainers" tag is set on this, so at least @xet7 should have push rights to the source branch in our fork. I'm also ok with someone else starting a new PR based on this, using their own fork.

**Pull request closed without merging**
