### PR TITLE
Yevhenii

### PR DESCRIPTION
**Pull request by ipyramiddev**
Added the ability to customize wekan's strings.

### CODE REVIEW

**Comment by xet7** [comment]
Hmm? I don't understand for what purpose this is.

**Comment by xet7** [comment]
@mfilser @helioguardabaxo 

Do you understand what is this for?

**Comment by mfilser** [comment]
It's a feature to add custom language translation by the server admin.
But i would not merge it because changes in Dockerfile and docker-compose.yml arent't needed, and also not the file in custom_data, it's just an example which should be at a wiki.

**Comment by xet7** [comment]
Translations for non-English should be done at https://explore.transifex.com/wekan/wekan/
so they are understanable in those languages.

**Pull request closed without merging**
