### PR TITLE
Additional label colours & fields

### PR DESCRIPTION
**Pull request by rjevnikar**
Add additional label colours (from pull by JamesLavin) and add Assigned & Requested By text fields.
Add delete board feature (#833)

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1679)

### CODE REVIEW

**Comment by xet7** [comment]
@rjevnikar 

Thanks a lot for your amazing work!

It would be much easier if you could create separate pull request for each feature, because some of these features are ready, and some are not. That way I could test and merge them separately. Having them together in one pull request means that all features need to be ready before merging, and it's harder to test in what feature each bug is.

1) Additional label colors: Seems to work, I'll need to test with export/import later.

2) Board Delete: Seems to work, but it should be in All Boards / Recycle Bin - at right side of Restore Board buttons. delete-board button seems to not be translated, there is still text delete-board when Wekan is running, instead of text Delete Board.

3) Assigned & Requested By text fields: add buttons does not work, when I have existing Wekan data and added your feature, maybe [migration is missing](https://github.com/wekan/wekan/issues/807#issuecomment-390385631).

Wekan card originally looks like this:
before

After adding Assigned & Requested By text fields it looks like this:
after

So layout is broken.

**Comment by xet7** [comment]
After migration added, Reguested By / Assigner By Add-buttons don't work yet.

**Comment by xet7** [comment]
@rjevnikar 

Thanks, you have great progress!

Now in browser right client / Inspect Element / Console, there is these error about multiple templates:
multiple-templates

**Comment by xet7** [comment]
@rjevnikar

Thanks, great progress!

- Card layout is now fixed
- You did add Delete Board button to All Boards / Recycle Bin, but it should be on right side, like this: `Board name [Restore Board] [Delete Board]`, and Delete Board button does not work yet.
- Assigned By / Received By Add-buttons do not work yet
- Delete Board button is not yet removed from single Board hamburger menu

**Comment by rjevnikar** [comment]
Thanks for your patience @xet7 .
I think I have addressed everything, but now Travis CI build has failed.
I ran eslint using npm, and didn't get any errors.

**Comment by xet7** [comment]
@rjevnikar 

That Travis build error is my fault, I copied newest Sandstorm fork version of Node.js from Sandstorm to Wekan server, and forgot to update checksum. I will fix it.

**Pull request merged**
