### PR TITLE
Fixed bug (rule doesn't move card to top/bottom) #2501

### PR DESCRIPTION
**Pull request by road42**
card.move needs boardId as first parameter

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2502)

### CODE REVIEW

**Comment by dieTausendsassa** [comment]
But, move card to top/bottom doesn't work. 
See also issue #2289

**Comment by road42** [comment]
The fix was released with: v2.85

**Comment by dieTausendsassa** [comment]
We are using release v2.86 and card move tob/bottom doesn't do anything ...

**Comment by road42** [comment]
@dieTausendsassa Yes that is right. The buttons from the interface are not fixed in this release. Just the actions you can use in rules.
But I had a look into the sourcecode. The error is the same, and I'll do another PR for this later.

**Comment by dieTausendsassa** [comment]
great!

**Pull request merged**
