### PR TITLE
adding checklist & card dependency features

### PR DESCRIPTION
**Pull request by andersonlin**
* adding checklist features
* adding dependencies cross boards

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/576)

### CODE REVIEW

**Comment by rnjailamba** [comment]
@andersonlin please try again or share a fork with the checklist feature working.

**Comment by brylie** [comment]
@andersonlin would you consider signing the contributors agreement? We would be interested to see you checklist code in Wekan core 😃

**Comment by brylie** [comment]
@andersonlin we are really excited about your work. When do you think it is ready for review and merge?

**Comment by brylie** [comment]
This PR would close #129, #298, and #597

**Comment by danger89** [comment]
Did he sign?

**Comment by brylie** [comment]
No response yet. Two other options might be:
- relax the contributor agreement requirement for Wekan
- re-implement the feature

**Comment by danger89** [comment]
@brylie what about the user accept the agreement automatically when submitting a PR? I think the developer don't mind.

**Comment by danger89** [comment]
Let's say like this : he did all the effort, programming / testing and submitted the pr, do you really think he won't allow you to add the code to the wekan core?

**Comment by brylie** [comment]
The contributor agreement basically signs Copyright permissions directly to Maxime Quandalle or any organization Maxime chooses. A simple Pull Request may not explicitly assign the Copyright privileges, since the PR code does not contain a license file.

It is not my decision to make, but is worth clarifying the purpose of the [Wekan contributor agreement](https://cla-assistant.io/wekan/wekan?pullRequest=576).

**Pull request closed without merging**
