### PR TITLE
card setting customization

### PR DESCRIPTION
**Pull request by 2020product**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2922)

### CODE REVIEW

**Comment by 2020product** [comment]
Hi @xet7 
Please review the code
@2020product 
thanks

**Comment by 2020product** [comment]
Hi @xet7
How are you?
I don't know well why you are not reviewing the code.
Did you solve the issues?
Please let me know about this and if there are issues.
Thanks and regards
@2020product

**Comment by xet7** [comment]
@2020product 

There is already Wekan Board Settings / Card Settings / Show on Card where it's possible to hide dates, subtasks, etc, and it's already at newest production Wekan Snap on your server.

Also, there are these not needed changes to:
- package-lock.json
- package.json

What are you trying to add to Wekan that is not already at Wekan?

**Comment by 2020product** [comment]
Thanks for contacting me
Kaspar said me that copy button is not working and design was not build as he want, such as comment and description.
So I added it in this pull request.

**Comment by xet7** [comment]
@2020product 

Thanks for info, I did not know that Copy Card Link to Clipboard button did not work, I fixed it. Fix will be in next Wekan release.

I did [receive feedback that Description is missing](https://github.com/wekan/wekan/issues/2918#issuecomment-582346577), so I added it back. How would users know that it's place for description, if that text would be hidden?

I did add previously your Comment changes, but then received feedback, that [adding comments does not work](https://github.com/wekan/wekan/issues/2918). So I had to add back the previous code where adding comment did work.

**Comment by 2020product** [comment]
Hi

I changed this part in inlinedform.jade
I committed this part in pull request "card setting customization #2922"
Please review the code.
Maybe this will fix the issue "adding comments does not work. "
I think this part did not merge into master branch before.
comment is working very well on my local after changing inlinedform.jade

Screen Shot 2020-02-10 at 8 02 43 PM

**Comment by xet7** [comment]
@2020product 

There is a lot of other unrelated code in this pull request that I can not merge, because there is already settings for hiding some parts of a card.

When you make a new pull request, please create a new fork, and only add small changes that are not yet in Wekan. Not anything that has previously already been merged.

**Comment by xet7** [comment]
@2020product 

About that inlinedform: I had that change previously added to Wekan, it did work on my laptop, but not for some Wekan users, so I had to revert it. Because current comment form works, I don't know is there any reason to change it. Hiding comment form so that it needs to be clicked first to open it makes it require more clicks.

**Comment by e-stoniauk** [comment]
I can see that we can hide some elements now but if you compare with https://i.imgur.com/UCDZM3u.png (this is compact and clean) and this is how it looks when hiding the elements: https://drive.google.com/file/d/1ObOSCmSDNJW0BzhQpHSIKFzrtDYGv-oa/view

**Comment by 2020product** [comment]
Hi Lauri I committed the fixed code in pull request #2922I really don’t know why you did not merge this pull request.All feature to provide in video is working well on my local.I will show you it using TeamViewer or anydesk if you want. Best Sent from Mail for Windows 10 From: e-Stonia DevelopmentSent: Tuesday, February 11, 2020 7:13 AMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) I can see that we can hide some elements now but if you compare with https://i.imgur.com/UCDZM3u.png (this is compact and clean) and this is how it looks when hiding the elements: https://drive.google.com/file/d/1ObOSCmSDNJW0BzhQpHSIKFzrtDYGv-oa/view—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@e-stoniauk 

I will test how it looks when I remove grouping of card parts.

@2020product 

I did not merge it because you had many changes at some one pull request, merging it directly would have broken Wekan. You should have one small change in one pull request.

**Comment by 2020product** [comment]
HiI can not understand you wellI will not create the pull request again. Sent from Mail for Windows 10 From: Lauri OjansivuSent: Tuesday, February 11, 2020 12:20 PMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @e-stoniaukI will test how it looks when I remove grouping of card parts.@2020productI did not merge it because you had many changes at some one pull request, merging it directly would have broken Wekan. You should have one small change in one pull request.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by 2020product** [comment]
Pull request #2922 is correct code to test on my local.Why didn’t you merge it into master branch?I can not understand Sent from Mail for Windows 10 From: Lauri OjansivuSent: Tuesday, February 11, 2020 12:20 PMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @e-stoniaukI will test how it looks when I remove grouping of card parts.@2020productI did not merge it because you had many changes at some one pull request, merging it directly would have broken Wekan. You should have one small change in one pull request.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

Next version of Wekan fixes these.

**Comment by 2020product** [comment]
So what can I do?It is ok? Sent from Mail for Windows 10 From: Lauri OjansivuSent: Tuesday, February 11, 2020 4:15 PMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productNext version of Wekan fixes these.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

Yes it is OK. I have made fixes. You will have automatic update sometime today, please wait while I'm building release packages.
https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v378-2020-02-12-wekan-release

**Comment by 2020product** [comment]
Ok, thanks for your replyHave a good day Sent from Mail for Windows 10 From: Lauri OjansivuSent: Tuesday, February 11, 2020 4:43 PMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productYes it is OK. I have made fixes. You will have automatic update sometime today, please wait while I'm building release packages.https://github.com/wekan/wekan/blob/master/CHANGELOG.md#v378-2020-02-12-wekan-release—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

If you like to fix something else in Wekan, you can add a new pull request.

For some pull requests, I need to do some fixes so that it works in Wekan.

Just keep trying, that way you will get success.

**Comment by 2020product** [comment]
All features is working well on my localI don’t understand well how I try for success. Sent from Mail for Windows 10 From: Lauri OjansivuSent: Tuesday, February 11, 2020 5:14 PMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productIf you like to fix something else in Wekan, you can add a new pull request.For some pull requests, I need to do some fixes so that it works in Wekan.Just keep trying, that way you will get success.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

Wekan v3.78 released. If your server has not yet automatically updated yet, you can update immediately manually with:
```
sudo snap refresh
```
Please test does it work well enough now.

**Comment by 2020product** [comment]
All code to commit in pull request #2922 did not merged into master branch.Why are there happen?I don’t know well how commit code from my local to GitHub.All code is to be committed In Pull request #2922Why?I don’t know well. Sent from Mail for Windows 10 From: Lauri OjansivuSent: Tuesday, February 11, 2020 5:59 PMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productWekan v3.78 released. If your server has not yet automatically updated yet, you can update immediately manually with:sudo snap refreshPlease test does it work well enough now.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

Your pull request did break Wekan, that's why I could not directly merge it.
Your pull request had much extra code that was different than newest Wekan master branch. There was extra files like package.json, package-lock.json, changes to Card Settings menu that were different than in newest Wekan.

1. Rename your current directory:
```
mv wekan wekan-old
```
2. Delete your fork at https://github.com/2020product/wekan

3. Then create new fork of https://github.com/wekan/wekan to https://github.com/2020product/wekan

4. Clone your fork: `git clone git@github.com:2020product/wekan.git`

5. Build Wekan, and see what other changes are still needed, that are not yet in Wekan.

6. Make small changes, like move Attachement link to other place, or some other small change.

7. Commit changes and push to your repo.
```
git add --all
git commit
git push
```
8. In GitHub webpage, create pull request.

**Comment by xet7** [comment]
@2020product 

Each change should be small, and in separate pull request. Example:

1. Create branch for feature:
```
cd wekan
git checkout master
git checkout -b feature-comment-box-size-change
# edit files to change some css
git add --all
git commit
# write description of commit
git push --set-upstream origin feature-comment-box-size-change
```
And at GitHub repo https://github.com/2020product/wekan change from dropdown to branch feature-comment-box-size-change and click Create Pull Request.

Then, for other feature:
```
git checkout master
git checkout -b feature-something
# edit files to change some css
git add --all
git commit
# write description of commit
git push --set-upstream origin feature-something
```
And at GitHub repo https://github.com/2020product/wekan change from dropdown to branch feature-something and click Create Pull Request.

This way you can make small pull requests for each small changes. These are much easier for me to check, and if it works in Wekan, I can directly merge it.

Your previous big pull request had so many changes, that I could not directly merge it, there was extra files, and I had to manually copy some parts of it to Wekan.

You do not have direct commit access to Wekan. Pull Request means, that you send small code change, that shows in Wekan repo https://github.com/wekan/wekan/pulls , and I do check each pull request does it work. If it works, I can directly add it to Wekan, by merging it directly.

**Comment by 2020product** [comment]
Hi @xet7I can not understand well what you mean.I committed code like so before.So I send you my all code.This is code to change wekan 3.75.Please check and I hope you will commit code to GitHub. https://github.com/2020product/webapp/tree/wekan Sincerely@2020product  Sent from Mail for Windows 10 From: Lauri OjansivuSent: Wednesday, February 12, 2020 4:33 AMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productEach change should be small, and in separate pull request. Example:Create branch for feature:cd wekangit checkout mastergit checkout -b feature-comment-box-size-change# edit files to change some cssgit add --allgit commit# write description of commitgit push --set-upstream origin feature-comment-box-size-changeAnd at GitHub repo https://github.com/2020product/wekan change from dropdown to branch feature-comment-box-size-change and click Create Pull Request.Then, for other feature:git checkout mastergit checkout -b feature-something# edit files to change some cssgit add --allgit commit# write description of commitgit push --set-upstream origin feature-somethingAnd at GitHub repo https://github.com/2020product/wekan change from dropdown to branch feature-something and click Create Pull Request.This way you can make small pull requests for each small changes. These are much easier for me to check, and if it works in Wekan, I can directly merge it.Your previous big pull request had so many changes, that I could not directly merge it, there was extra files, and I had to manually copy some parts of it to Wekan.You do not have direct commit access to Wekan. Pull Request means, that you send small code change, that shows in Wekan repo https://github.com/wekan/wekan/pulls , and I do check each pull request does it work. If it works, I can directly add it to Wekan, by merging it directly.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@e-stoniauk @2020product 

Newest is Wekan v3.78, it's at your Wekan Snap server. It has compact small layout. In Boatd Settings/Card Settings/Show on card you can disable many parts of card, it's very close to your screenshot you linked at https://drive.google.com/file/d/1ObOSCmSDNJW0BzhQpHSIKFzrtDYGv-oa/view%E2%80%94You
In Card Settings you can also hide Description Title, so only Description Text is visible. I added that feature yesterday.

Is there still something missing that is not yet in newest Wekan?

**Comment by xet7** [comment]
Screenshot_20200212-171753


Screenshot_20200212-171822

**Comment by 2020product** [comment]
Check code that I send you. Sent from Mail for Windows 10 From: Lauri OjansivuSent: Wednesday, February 12, 2020 7:19 AMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

Please ask your boss are changes mentioned above in screenshots enough, or is some change still missing. When I look at screenshots above, it's very close to your screenshot.It is critical to ask, because he did undertand previously to write what is missing. I need to know if current screenshots above are not good enough, and why.

You have sent same old big amount of code to me many times. I have added those parts to Wekan that do work well, and don't break Wekan card layout. Some of your changes did not work, so I did not add those. I have read your code many times, and I do not know what specific lines of code you mean I should read, that U would know what is still missing.

**Comment by 2020product** [comment]
There are a lot of issues in wekan-3.78
This is the photo to run wekan on my local

**Comment by xet7** [comment]
@2020product 

You have old Wekan version. Here is how to get newest version: https://github.com/wekan/wekan/pull/2922#issuecomment-585173538

Newest Wekan looks like this: https://github.com/wekan/wekan/pull/2922#issuecomment-585256065

**Comment by 2020product** [comment]
I don’t know why newest wekan looks like so.You must know itI committed code and sent you code to change wekan-3.75.Don’t ask me Sent from Mail for Windows 10 From: Lauri OjansivuSent: Wednesday, February 12, 2020 10:43 AMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productYou have old Wekan version. Here is how to get newest version: #2922 (comment)Newest Wekan looks like this: #2922 (comment)—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product 

Newest Wekan looks like that, because I have already added most of your code to newest Wekan.

Your development code is still old. You should rename your old repo, delete your GitHub fork, and make new fork. Please ask some other developers in your team to help you with getting newest code. Those other developers can read messages above and help you understand, how to get newest Wekan code.

Info about Git commands:
https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdf

Some info is also here, so after you have deleted your Wekan fork, you can make a new fork, and then build and test Wekan:
https://www.youtube.com/watch?v=rgbCcBNZcdQ

**Comment by 2020product** [comment]
I don’t know Sent from Mail for Windows 10 From: Lauri OjansivuSent: Wednesday, February 12, 2020 11:10 AMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productNewest Wekan looks like that, because I have already added most of your code to newest Wekan.Your development code is still old. You should rename your old repo, delete your GitHub fork, and make new fork. Please ask some other developers in your team to help you with getting newest code. Those other developers can read messages above and help you understand, how to get newest Wekan code.Info about Git commands:https://github.github.com/training-kit/downloads/github-git-cheat-sheet.pdfSome info is also here, so after you have deleted your Wekan fork, you can make a new fork, and then build and test Wekan:https://www.youtube.com/watch?v=rgbCcBNZcdQ—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by xet7** [comment]
@2020product

Newest Wekan Snap version already has your changes, and also my improvements to that code, making visually more polished. All these changes are now ready for testing. It works very well.

You can add same settings to Wekan Snap version like here at screenshots:
https://github.com/wekan/wekan/pull/2922#issuecomment-585256065

Please ask your boss and other team members to test newest Wekan Snap version. They should check is something missing.

**Comment by 2020product** [comment]
I can not do it That’s why I am working as free now.My boss is not pay the money. @kasparSo I can not do itDon’t reply againThanks for your time Sent from Mail for Windows 10 From: Lauri OjansivuSent: Wednesday, February 12, 2020 11:28 AMTo: wekan/wekanCc: 2020product; MentionSubject: Re: [wekan/wekan] card setting customization (#2922) @2020productNewest Wekan Snap version already has your changes, and also my improvements to that code, making visually more polished. All these changes are now ready for testing. It works very well.You can add same settings to Wekan Snap version like here at screenshots:#2922 (comment)Please ask your boss and other team members to test newest Wekan Snap version. They should check is something missing.—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

**Pull request closed without merging**
