### PR TITLE
New Feature: Copy many

### PR DESCRIPTION
**Pull request by erikturk**
I want to be able to add multiple cards from a list. We create a "template card" that has the appropriate checklists, and then make multiple copies of that card substituting the title and description from a user supplied list in json format.

I've added "Copy Multiple Cards" to the Hamburger menu for Cards.

When you paste a list like:

[ {"title":  "First Card title", "description":"First Card Description"}, {"title":"Second Card Description","description":"Second Card Description"},{"title":"Last Card title","description":"Last Card description"}]

The menu option will create 3 new cards in the list that you select.

~~The commit includes i18n/en-GB.i18n.json - but shouldn't based on the contrib guidelines.~~ removed in last commit

First time contributor. Feedback welcome (How do I get rid of the crazy/not useful/embarrassing commit messages that I used when developing this? Will they be part of the project forever?)

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1470)

### CODE REVIEW

**Comment by xet7** [comment]
@erikturk

Adding feature to Wekan is huge and excellent. There is nothing embarrassing, I also fix typos etc all the time.

Here's how to remove commits:
https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request

Remove all changes to readme and changelog.

New strings are added in pull request to English base translation file wekan/i18n/en.i18n.json 
Other translations are done at https://www.transifex.com/wekan/wekan/ , so remove other translations from pull request.

Thanks!

**Comment by erikturk** [comment]
Hi - thank you for your work in managing Wekan development. It was certainly very easy to find what to add and where. 

My Travis-CI build is failing because of mentions of swimlanes. I know this is a new feature.

Am I building against an incorrect (or out of date) version of Wekan? What can I do to get my pull request to pass the Travis-CI check? Specific recommendations are appreciated (Don't do it for me, but please tell me what to do - I'm lost at this point, and would appreciate guidance.)

Thanks.

**Comment by xet7** [comment]
@erikturk 

It seems that you are implementing Checklist Templates #904 

Using this kind of JSON in wekan/i18n/en.i18n.json file and JSON validator like https://jsonlint to check for JSON errors: 

```
        "copyManyCardPopup-title": "Copy Checklist Template to Many Cards",
        "copyManyCardPopup-title-instructions": "Destination Card Titles and Descriptions in this JSON format: [ {\"title\": \"First Card title\", \"description\":\"First Card Description\"}, {\"title\":\"Second Card Description\",\"description\":\"Second Card Description\"},{\"title\":\"Last Card title\",\"description\":\"Last Card description\"} ]",
```

Do the following:

1) Rename everywhere in your added code variable names, translation variable names, and user visible texts: Copy Multiple Cards => Copy Checklist Template to Many Cards

2) In below screenshot "Copy Checklist Template to Many Cards" popup change:
- Copy Multiple Cards => Copy Checklist Template to Many Cards
- Title: => Destination cards and titles in this JSON format:
- Input box: Your example JSON text, like in screenshot below as pre-filled, and translatable like in wekan/i18n/en.i18n.json above

checklist-templates

**Comment by erikturk** [comment]
Thank you for this feedback! I'm excited to make these changes. You'll see an update soon!

**Comment by xet7** [comment]
@erikturk 

Thanks, I will test.

**Comment by xet7** [comment]
@erikturk 

There is still variables with names like copyManyCard in translations etc. Those should be renamed to like "copyChecklistTemplateToManyCards" or similar. There should not be anything that has any text like copyManyCard, it's not clear enough.

**Comment by erikturk** [comment]
Thank you for the feedback. I'll get right on it

**Comment by erikturk** [comment]
Ready again for your review. Thank you for your patience and comments. Thank you for your efforts in coordinating wekan development.

**Comment by xet7** [comment]
@erikturk 

Thanks a lot, now it's perfect ! I will merge it soon and release new version of Wekan with that feature. Developers like you are the worth gold and [time well spent](https://blog.wekan.team/2018/02/time-well-spent/index.html) for me.

**Pull request merged**
