### PR TITLE
Add Feature: Planning Poker

### LINKED ISSUE #3751: Feature Request: Planning Poker
Remote working is here to stay and Wekan provides an excellent tool for remote workers. A few teams in our organisation have asked for a Planning Poker functionality and we believe this could be a good functional extension in Wekan. A remote Planning Poker session is, of course, possible with other tools like specialized websites and Skype or MS Teams like functionality but would it not be nice to incorporate things withing Wekan?

Planning Poker works like a kind of Voting-systematic with a closed set of answers. The current Voting-functionality in Wekan works with only 2 possible answers 'For' and 'Against' and I believe it should be fairly easy to extend the possible answers with the usual deck of poker-cards. Using the current Voting-functionality also, optionally, shows and store what every member voted so this could be a good starting point to start a discussion with that specific member. 

The Wikipedia-page shows a few decks of cards and further explanation. I would suggest using the  sequence: 0, ½, 1, 2, 3, 5, 8, 13, 20, 40, 100, and optionally a ? (unsure), an infinity symbol (this task cannot be completed).
https://en.wikipedia.org/wiki/Planning_poker

Thanks for attention and looking forward to your reaction.

### PR DESCRIPTION
**Pull request by helioguardabaxo**
This PR implements Planning Poker in a card and resolves #3751.

Features:
 - End date: Could starts with/with out end date.
 - Finish (manually): finish button ends Planning Poker and set current date to end date (only board admin's)
 - Results: shows votes and who voted whom
 - Replay:  replay button restarts Planning Poker (only board admin's)
 - Set estimation (manually): after team consensus, sets estimation and shows in minicard

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3836)

### CODE REVIEW

**Comment by yarons** [comment]
Is it Poker like the popular card game?

**Comment by xet7** [comment]
@yarons 

Sorry, no. It's Scrum Poker https://en.wikipedia.org/wiki/Planning_poker

**Comment by mfilser** [comment]
@yarons
Did you already had a look at the resolved issue above?

**Comment by xet7** [comment]
I did open this issue:
Bug: Planning Poker Setting End Date only works in English https://github.com/wekan/wekan/issues/3837

AFAIK it is not fixed yet.

**Comment by yarons** [comment]
> @yarons
> 
> Sorry, no. It's Scrum Poker https://en.wikipedia.org/wiki/Planning_poker

Why not? Planning Poker is called that way because of the popular game, when translating I need a known reference since Poker could also be a conjucation of poke/poking, so Planning Poker is definitely named after the popular card game.

**Comment by xet7** [comment]
@yarons 

Yes, but I'm not familiar with poker rules, about can original poker be played with this. I presume this feature is for Planning Poker rules only.

**Pull request merged**
