### PR TITLE
Add isAdmin to user Schema

### LINKED ISSUE #924: Add Feature: Set admin on first run
When you freshly install Wekan from the bare metal, there's no default user and no admin account. So i would suggest to create a first user / admin account on the first run, by setting a env variable to something like `FIRST_USER =potus44:y3sw3c4n:bo@whitehouse.gov`.

### PR DESCRIPTION
**Pull request by Zokormazo**
The code for making first user an Admin was there, but missing isAdmin field on userSchema.

Fixes #924

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/970)

### CODE REVIEW

**Comment by xet7** [comment]
@Zokormazo 

You need to first check that Wekan is not running at Sandstorm, and only then add first user as Admin, otherwise I cannot accept this pull request. See:
https://github.com/wekan/wekan/blob/devel/sandstorm.js

**Comment by Zokormazo** [comment]
Ok

**Comment by xet7** [comment]
So it needs to check environment variables first, is it running on Sandstorm.

**Comment by Zokormazo** [comment]
Done

**Pull request merged**
