### PR TITLE
Use simple border at My Cards

### PR DESCRIPTION
**Pull request by helioguardabaxo**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3475)

### CODE REVIEW

**Comment by helioguardabaxo** [comment]
@jrsupplee 
I tried to modify board style.
What do you think?

**Comment by xet7** [comment]
I have not looked it yet, but shadows are very hard for those that have low vision, so they are not used in Wekan. Wekan needs to have clear color differences, not shadows.

**Comment by xet7** [comment]
So please remove shadow.

**Comment by helioguardabaxo** [comment]
Could I use gradient or simple border is the better way?

**Comment by xet7** [comment]
Simple border is the better way.

**Comment by xet7** [comment]
Gradients are only in some themes. Sometime I will add global theme, so it's like board theme but for all non-single board pages.

**Pull request merged**
