### PR TITLE
bump: mongodb -> 3.6.2

### PR DESCRIPTION
**Pull request by blaggacao**
https://github.com/mongodb/node-mongodb-native/releases

Unfortunately this doesn't bump the transient dependency on `mongodb` of `gridfs-stream`, see: https://github.com/aheckmann/gridfs-stream/pull/150 :confused: 

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3268)

### CODE REVIEW

**Comment by xet7** [comment]
@blaggacao  @urakagi 

Related could be change to GridFS is not-yet-done change to ostrio-files by @urakagi :
- Would make possible to upload and download attachments that have Chinese characters in filenames
- Would make possible to save attachments outside of database, like Google Drive etc

Related issues and code here:
- https://github.com/wekan/wekan/issues/3110#issuecomment-633256006 
- https://github.com/wekan/wekan/pull/3217
- https://github.com/wekan/wekan/tree/feature-ostrio-files

Would change to ostrio-files also update `gridfs-stream` ?

**Comment by blaggacao** [comment]
@xet7 Isn't there any quick-fix we can procure for: https://github.com/wekan/wekan/issues/3262#issuecomment-690826333 ? Just to unblock connecting to a remote mongodb (> v4.x)...

I can also do the fork and apply the patches, if that's not something that should live under the `wekan` org. If it's an ultra-short lived work around, that would be ok. However I can't probably aspire to maintain grid-stream long term &mdash; more so that I have little ongoing experience with javascript...

**Comment by xet7** [comment]
@blaggacao 

Please make changes directly to this fork https://github.com/wekan/gridfs-stream

**Comment by blaggacao** [comment]
@xet7 Thank you! Best solution ever! I'll get my hands dirty straight on... :+1:

**Comment by xet7** [comment]
@blaggacao 

You can also make pull request to https://github.com/wekan/wekan so it changes to use that fork of https://github.com/wekan/gridfs-stream

**Pull request merged**
