### PR TITLE
Update et-EE.i18n.json

### PR DESCRIPTION
**Pull request by andrewlytvyn**
Translated on another service

### CODE REVIEW

**Comment by xet7** [comment]
You should translate directly at web interface of https://transifex.com/wekan/wekan or upload your JSON file there. Only changes to original wekan/i18n/en.i18n.json are done with pull requests, when adding new features. I do download all translations from Transifex and commit to git repo before making new release.

Thanks!

**Comment by andrewlytvyn** [comment]
How to import json file into transifex?

**Comment by xet7** [comment]
@andrewlytvyn 

It seems you have already made changes at Transifex. You don't need to do anything. Please wait for next WeKan release v5.94 release sometime later today, it will include your translations. Thanks!

**Comment by xet7** [comment]
Hmm, it seems you did changes only to JSON file directly. Just a moment I'll try to figure out how to upload those.

I hope next time you translate directly at web interface at https://transifex.com/wekan/wekan

**Comment by xet7** [comment]
@andrewlytvyn 

I added your translations to WeKan. They will be in next WeKan release.

**Comment by xet7** [comment]
@andrewlytvyn 

You still have 3 strings you have not translated. Please login to https://transifex.com/wekan/wekan and at Estonian language click Translate button. Save those untranslated at web interface. Then I can add those to WeKan. Please do not make pull request.

**Comment by xet7** [comment]
After you have translated everything from Estonian language, I will make new WeKan release.

**Comment by andrewlytvyn** [comment]
I understand, I will only use transifex)

**Pull request closed without merging**
