### PR TITLE
Devcontainer, reduce image size and other necessary changes for development

### PR DESCRIPTION
**Pull request by mfilser**

### CODE REVIEW

**Comment by xet7** [comment]
@mfilser 

But but... Debian 11 is old, very vulnerable version of Linux. Previosly, I have compared Debian and Ubuntu, and at that time Debian had many vulnerabilities, and Ubuntu had none. WeKan uses Ubuntu 24.04 based container https://github.com/wekan/wekan/blob/main/Dockerfile#L1 . In Meteor WeKan, security is more important than container size.

If size really is a problem, I try to get more progress on WeKan Studio, where Node+MongoDB+WeKan is changed to one executeable that currently size is 9.5 MB. https://github.com/wekan/wekanstudio

**Comment by xet7** [comment]
@mfilser 

When previously testing distos, Meteor WeKan had some problems when using Alpine Linux. WeKan has used Ubuntu for a long time, because it has worked bes.

**Comment by xet7** [comment]
@mfilser 

If using Debian, I think current version is Debian 12.

**Comment by xet7** [comment]
If anyone else is reading this, here is more details:

@mfilser has contibuted major features to WeKan, like major speedups at https://github.com/wekan/wekan/issues/5000 , and very many other features and fixes.

WeKan Studio https://github.com/wekan/wekan is currently my small prototype of future WeKan, where is not even login possible yet. It can not replace Meteor WeKan yet.

**Comment by mfilser** [comment]
@xet7
Thank you for your hints.

I saw already in the main Dockerfile that the Ubuntu base image changed often, but not in the devcontainer directory Dockerfile, so I thougt you don't care if the version there.

For development Debian is good, i never had problems with it. I have more often problems with Ubuntu at development because the repositories are changing more often.

**Comment by xet7** [comment]
@mfilser 

Well, you are right, actually I don't care, because I'm not using this devcontainer.

**Pull request merged**
