### PR TITLE
[Feature] Estimate Field for Cards

### PR DESCRIPTION
**Pull request by jLouzado**
Hello,

I'm trying to implement a feature where a user can set an estimate for how long a task (card) will take.

Reference Image]

The problem is that the field shows up (it's currently initialized to 5, just to test the view), but I can't get the 'Edit Form' to open up. 

I've been trying but I can't get my head around the `Popup.open` system in the code. Any help would be greatly appreciated.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/830)

### CODE REVIEW

**Comment by jLouzado** [comment]
@xet7 if you're busy is there anyone else who could spare a minute to assist me please?

**Comment by ocdtrekkie** [comment]
So, here's my question: What functionality is this field supposed to have? Would it not make more sense to instead focus on the more general "custom field" feature in #802?

Or will this tie into some larger project management view, where one can lay out the tasks, prerequisites, and time required?

**Comment by jLouzado** [comment]
@ocdtrekkie I'm working on the general 'custom field' case as well but I'm building a custom solution for some clients and trying to see if any of that code is useful to the wekan community as well.

I'm also new to Wekan, if I could get some help with the basics then I'd be able to work on Wekan features more easily.

**Comment by jLouzado** [comment]
@dwrensha could I please get some help with this feature?

Promise I'll write documentation about it so people can just be pointed to it next time. :D

**Comment by ocdtrekkie** [comment]
@jLouzado David is primarily only involved in Sandstorm.io fixes for Wekan. Developers who are working on this repository will certainly notice the PR when they have time.

**Comment by jLouzado** [comment]
Closing to focus on the custom fields implementation.

**Pull request closed without merging**
