### PR TITLE
Hopeful fix for i18n not working in `onRendered()`

### PR DESCRIPTION
**Pull request by jrsupplee**
* Remove the i18n initialization code from an `autorun()` block
* Add some console statements to help with debugging production.
* Add functions to `Boards` for label colors and color mapping

Issue #2074

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3519)

### CODE REVIEW

**Comment by xet7** [comment]
@jrsupplee 

In newest Wekan I just released, when I select some other language, it does not change immediately. For Snap version, it only changes after reloading webpage. For Sandstorm, it does not change at all, it stays English. I will look sometime later should I revert this.

**Comment by jrsupplee** [comment]
@xet7 

I noticed this too. I will try to look at it today

**Comment by yangjy666** [comment]
> @jrsupplee
> 
> In newest Wekan I just released, when I select some other language, it does not change immediately. For Snap version, it only changes after reloading webpage. For Sandstorm, it does not change at all, it stays English. I will look sometime later should I revert this.

I found it

**Comment by yangjy666** [comment]
I found that the v6.46 version still has this problem.

**Comment by jrsupplee** [comment]
Tried French and Arabic on 6.46 and it seems to be working fine.

**Pull request merged**
