### PR TITLE
additional vote features

### PR DESCRIPTION
**Pull request by NicoP-S**
- adds the total vote thing #3047 
- adds option "Allow non board members to vote" ( for public boards )
- display vote result on minicard

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3048)

### CODE REVIEW

**Comment by xet7** [comment]
Hi,
please change these in all code variables and English translation:
- Public vote => Show who voted what
- Allow non board members => Allow anonymous vote on public board

Also, currently there only can be one anonymous vote on public board. Even when accessing board from different IP address to set second anonymous vote, it modifies that original first anynymous vote. This is because for Meteor, there is only one anonymous user, it does not depend on IP address. For anonymous vote, there is no user listed in for or against. There could be, in theory, IP address of the anonymous voter.

**Comment by NicoP-S** [comment]
@xet7 ah damm. I missed to query of the User is logged in on public Board votes...
I will fix this asap. 
Naming of variables and text will be change too.
Thanks

**Comment by xet7** [comment]
If someone does anonymous vote on public board, it could be useful that they could input their name to that vote. For example:
(anonymous vote font awesome icon here) Alex (tooltip: ip address)

**Comment by xet7** [comment]
actually, ip address would better be visible, not in a tooltip

**Comment by xet7** [comment]
Hmm, I don't know. Maybe visually better still in a tooltip.

**Comment by xet7** [comment]
Oops sorry I merged it early. Anyway, please add additional changes in new pull request.

**Comment by xet7** [comment]
I think I will not revert this, it's just missing some additions.

**Comment by xet7** [comment]
Hmm, actually, I need to revert this, because it makes changes to database, and having this in-progress version would bring migrations issues.

**Comment by NicoP-S** [comment]
@xet7  my idea behind "allow non board members" was to allow logged in users to vote on public boards. I don't know how to handle not logged in User (anonym).

**Comment by xet7** [comment]
@NicoP-S 

Then you should check that user is logged in, so anonymous can not vote:
```
if (Meteor.user()) {
```

**Pull request merged**
