### PR TITLE
Always display attachment section for uploading file quickly

### PR DESCRIPTION
**Pull request by thuanpq**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1391)

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
I am not super fond of this change. It takes up like an inch and a half, since the current "Add attachment" button is a giant box. It pushes the most recent comment to nearly always be below the scroll point.

Is it possible we could shorten how large this section is if there's no attachments, while still making the Attachments section visible all the time?

**Comment by xet7** [comment]
@ocdtrekkie 

Those changes have been made to make it faster to add a lot of attachments. If you have improvements to CSS, then submit pull request :)

**Comment by ocdtrekkie** [comment]
I understand why. But as someone who rarely uses attachments in Wekan, the change has a very painful cost. I am not personally comfortable trying to improve it myself, but hoping perhaps my suggestion on how it can be improved might be useful to the person who made the PR.

**Comment by xet7** [comment]
@ocdtrekkie 

Discussion moved to #1328

**Pull request merged**
