### PR TITLE
remove short language conversion for t9n

### PR DESCRIPTION
**Pull request by qftgtr**
t9n/i18n tags are same now, see:
https://github.com/softwarerero/meteor-accounts-t9n/pull/129

---

This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/682)

### CODE REVIEW

**Comment by qftgtr** [comment]
This commit fixes issue [#681](https://github.com/wekan/wekan/issues/681)

**Comment by b447008888** [comment]
ds

**Comment by dwrensha** [comment]
https://github.com/wefork/wekan/pull/4 has a fix for this issue.

**Comment by dwrensha** [comment]
Fixed by https://github.com/wefork/wekan/pull/4, which has now been pulled in to this repo.

**Pull request closed without merging**
