### PR TITLE
Fix: Impossible to export board to excel where title exceeding 31 chars

### LINKED ISSUE #3589: Impossible to export board to excel - exceeding 31 chars
Wekan Snap installed, latest:

Wekan Version: 4.96.0
Meteor: 2.0
Node: 12.20.2
MongoDB: 3.2.22 (wiredTiger)
Linux x64 - 4.19.0-14-amd64

Problem description:
When on any board, going to Export board -> Export to Excel-> nothing happens, no excel is proposed to save.

Wekan Snap Logs:

Feb 19 13:27:55 wekan wekan.wekan[29662]: Worksheet name "Worksheet_name" exceeds 31 chars. This will be truncated
Feb 19 13:27:55 wekan wekan.wekan[29662]: (node:30887) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at ExporterExcel.build (models/exportExcel.js:228:8)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at models/exportExcel.js:43:21
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at doCall (packages/meteorhacks_picker.js:128:14)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at PickerImp._processRoute (packages/meteorhacks_picker.js:122:5)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at processNextRoute (packages/meteorhacks_picker.js:90:14)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at processNextRoute (packages/meteorhacks_picker.js:92:9)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at processNextMiddleware (packages/meteorhacks_picker.js:78:7)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at PickerImp._dispatch (packages/meteorhacks_picker.js:72:3)
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at packages/meteorhacks_picker.js:162:10
Feb 19 13:27:55 wekan wekan.wekan[29662]:     at /snap/wekan/1350/programs/server/npm/node_modules/meteor/promise/node_modules/meteor-promise/fiber_pool.js:43:40
Feb 19 13:27:55 wekan wekan.wekan[29662]: (node:30887) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 46)

### PR DESCRIPTION
**Pull request by Ben0it-T**
Fix #3589
- If board title is 31 chars or less, just add it in worksheet title
- If board title is over 31 chars, replace worksheet title by 'board'

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/4119)

### CODE REVIEW

**Comment by xet7** [comment]
@Ben0it-T 

This is not a good fix, to not show board title at all. I would prefer not to merge this.

Instead, you should split that over 31 characters title with Javascript string functions to more than one spreadsheet cell.

**Comment by xet7** [comment]
@Ben0it-T 

Also, check in generated spreadsheet that all text is visible. If text is not visible, use exceljs code to make that column wider.

**Comment by xet7** [comment]
@Ben0it-T

I have not yet checked are all custom fields, etc data exported to Excel. It would be better to export all board data that is possible to export (or what makes sense to be exportable).

**Comment by Ben0it-T** [comment]
@xet7 
No problem! You're the boss
The board title appears in the Excel worksheet (A1). I thought that was enough.
I'll close the PR.

**Comment by xet7** [comment]
@Ben0it-T 

Another question you could search answer for. Is the limit of 31 characters in:
a) Exceljs code? Is there possibility to save more that 31 characters with some other code?
b) File format? What are limits in one cell in LibreOffice, Excel, etc? Can you try how much cell can have text?
c) Is there any other spreadsheet code in Javascript or other programming language, that can write more text to one cell?

**Comment by xet7** [comment]
@Ben0it-T

Also, when saving data to other non-title cells, what if they are also over 31 characters? Does export work at all? Should all text be spit for 31 characters to each cell? Or is it possible to have more text per cell?

**Comment by Ben0it-T** [comment]
@xet7 
This isn't a exceljs problem. Normally exceljs both warning and truncating names to 31 chars. Worksheet name length seems to be hard coded into Excel at 31 characters.

For example, when i export a board with a title exceeds 31 chars :
`Nov  7 15:40:36 debian wekan.wekan[11118]: Worksheet name Very very long fantastic title of this board exceeds 31 chars. This will be truncated`
`Nov  7 15:40:36 debian wekan.wekan[11118]: (node:12566) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'properties' of undefined`
`Nov  7 15:40:36 debian wekan.wekan[11118]:     at ExporterExcel.build (models/server/ExporterExcel.js:183:8)`
==> Exceljs truncate worksheet name.
==> line 182: `const ws = workbook.getWorksheet(result.title);`
==> ws will be undefined

No problem with others cells:
- Number of characters that a cell can contain: 32k chars
- Column width: max 255 characters
- Row height: max 409 points

[export-board-excel-BGZ3yhCwXnTGoAcSF.xlsx](https://github.com/wekan/wekan/files/7492498/export-board-excel-BGZ3yhCwXnTGoAcSF.xlsx)

**Comment by Ben0it-T** [comment]
@xet7
The problem is that MS Excel doesn't allow worksheet name longer than 31 chars.
We can certainly split the board title to make it appear on several sheet (_with some JS_) but I'm not sure it's great...

For example 
worksheet

In this case, board title appears on two worksheet "Very very long fantastic title" + "of this board".
But worksheet "of this board" will be empty.

We can also keep the first x characters or leave exceljs truncate the title but that's not great either

worksheet 2

worksheet 3

honestly I don't really know what to do...

**Comment by mfilser** [comment]
If i could make a suggestion: I (personally) would prefer to write ...  at the end of the worksheet name (same as picture "worksheet 2"

**Comment by xet7** [comment]
Yes. I would think sheet name would be truncated like:
```
Sheet name with about 27 chars 1
```
Where 1 is sheet number, and there is space for numbered sheets to be 10, 100 etc

Then at actual sheet bigger cell, have full sheet name:
- Aligned to left
- If it does not fit to one cell, split and continue to next cell at right

**Comment by xet7** [comment]
Hmm sure board title can be centered etc

**Comment by xet7** [comment]
Also, for text in cells that is not title cell, please align to top left. Not bottom left. Thanks!

**Comment by Ben0it-T** [comment]
@mfilser @xet7 
Thank you for your answers
There are two (or more) "topics"
- worksheet name
- cell layout

For worksheet name,
If title has spaces, something like this should do the job 
```
let worksheetTitle = "Very very long fantastic title of this board";
if (worksheetTitle.length > 31) { 
  let words = worksheetTitle.split(" ");
  let tmpTitle = "";
  for (const i in words) {
    if(tmpTitle.length + words[i].length < 27) {
      tmpTitle += words[i] + " ";
    }
    else {
      break;
    }
  }
  worksheetTitle = tmpTitle + "...";
}
```
If title has no spaces... it will be ugly...

**Comment by mfilser** [comment]
Just an idea: Maybe hard replace the last 4 characters with one space and 3 dots.?

**Comment by Ben0it-T** [comment]
that's what I planned to do.
I'll watch at the end of the weekend with something like 
```
for(let i=0;i<words.length; i++) {
  if( words[0].length > 27 ) {
    tmpTitle = words[0].substr(0,27) + " ";
    break;
  }

  if(tmpTitle.length + words[i].length < 27) {
      tmpTitle += words[i] + " ";
    }
    else {
      break;
    }
}
worksheetTitle = tmpTitle + "...";
```

**Comment by Ben0it-T** [comment]
big day tomorrow
too late for me

**Pull request closed without merging**
