### PR TITLE
header png

### PR DESCRIPTION
**Pull request by oliver4u**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/654)

### CODE REVIEW

**Comment by AlexanderS** [comment]
Any explanation why you want to change the header logo?

**Comment by oliver4u** [comment]
For internal use. Boss's command. : )

Alexander Sulfrian <notifications@github.com>于2016年7月25日周一 下午6:34写道：

**Comment by ocdtrekkie** [comment]
@oliver4u As a suggestion, you shouldn't create a pull request asking to merge your whitelabeling/debranding into the main app. ;)

**Comment by oliver4u** [comment]
Sorry, false operation, newbie to Github ....

Jacob Weisz <notifications@github.com>于2016年7月27日周三 上午9:50写道：

**Pull request closed without merging**
