### PR TITLE
Change move-to-archive keyboard shortcut to '-', because of Ctrl + C shortcut

### PR DESCRIPTION
**Pull request by NadavTasher**
Ctrl + C from card text would cause the card to be archived :(

### CODE REVIEW

**Comment by mohammadZahedian** [comment]
why '-' ?
it is far in keyboard in one handed...
how about 'a' stands for a Archive

**Comment by NadavTasher** [comment]
'a' is already used for 'My issues only'.
Also the issue was that in combination with 'Ctrl' (e.g. when you copy text), the shortcut would trigger, which is why 'z' is not a good candidate either.

**Comment by mohammadZahedian** [comment]
@NadavTasher 

how about ' ` ' or ' q '
' ` ' means key below the ' esc '

**Comment by NadavTasher** [comment]
Yeah that could work

**Comment by NadavTasher** [comment]
Created https://github.com/wekan/wekan/pull/5589.

**Pull request merged**
