### PR TITLE
Some Turkish language fixes

### PR DESCRIPTION
**Pull request by xgame92**
OS should written as İS but not readable for turkish language. So I changed with long version.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1332)

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
Translation work needs to be done via Transifex.

**Comment by xgame92** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wekan/wekan/1332)*

**Comment by xgame92** [comment]
Contributor License Agreement  page is not properly loading.

**Comment by ocdtrekkie** [comment]
Please make your changes at: https://www.transifex.com/wekan/wekan/
Note how Wekan handles translations: https://github.com/wekan/wekan/wiki/Translations

@xet7 Is it possible to like, get a bot that automatically responds to i18n PRs?

**Comment by xet7** [comment]
@ocdtrekkie 

Yes, I added making a bot to [Roadmap](https://github.com/wekan/wekan/wiki/Roadmap).

**Pull request closed without merging**
