### PR TITLE
optimize login form layout & css

### LINKED ISSUE #452: Interaction issues on mobile
I see the following issues when using the board on iPhone and iPad 
1. Some places need tap twice to activate a "click", for example, the add label button on card detail view, and the a card need to be clicked twice to open the detail view 
2. Drag and drop not working

### PR DESCRIPTION
**Pull request by floatinghotpot**
add a div with box-shadow as container dialog of at-form and language select.

when in compact mode:
1. change dialog to full window.
2. change language select from absolute position to relative.
3. change logo to half size and float on top right.

[Review on Reviewable](https://reviewable.io/reviews/wekan/wekan/455)

### CODE REVIEW

**Comment by mquandalle** [comment]
Once again, thank you very much @floatinghotpot :-) The header title overflows on the logo on some languages like French:

capture d ecran 2015-12-26 a 21 57 02

**Comment by mquandalle** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/455)*

**Comment by floatinghotpot** [comment]
Now I set the width of the login form title h3 to calc(100% - 125px), it will wrap to avoid overlapping the logo.

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/455#-:-K6aeKmYkgBcsj1SmhLN:-248707301)*

**Comment by mquandalle** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/455)*

**Pull request merged**
