### PR TITLE
Global Search Update

### PR DESCRIPTION
**Pull request by jrsupplee**
* Add paging of results
* add new operators for searching(`comment`, `status`, `due`, `sort`, `created`, `modified`)
* text searches now search comments associated with cards

#2074 

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3492)

### CODE REVIEW

**Comment by xet7** [comment]
@jrsupplee 

As a note for any future pull requests: I do only push pull request translations changes of original base language `wekan/i18n/en.i18n.json` to Transifex, all other translations are done at https://transifex.com/wekan/wekan . Sending any other translations as pull request is not useful, because it will get overwritten by translations I download from Transifex.

**Comment by xet7** [comment]
@jrsupplee 

Thanks a lot for your amazing contributions!

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> As a note for any future pull requests: I do only push pull request translations changes of original base language `wekan/i18n/en.i18n.json` to Transifex, all other translations are done at https://transifex.com/wekan/wekan . Sending any other translations as pull request is not useful, because it will get overwritten by translations I download from Transifex.

It’s ok if they get overwritten.  Most of it was for testing

**Comment by xet7** [comment]
@jrsupplee 

It seems building Snap fails because of https://github.com/wekan/wekan/blob/master/client/components/main/globalSearch.js#L484 , see https://forum.snapcraft.io/t/userwarning-attempted-to-set-unknown-attribute-location-on-instance-of-container/22421 .

Could that code be changed to not use text `location` ?

**Comment by xet7** [comment]
Issues at:
- https://forum.snapcraft.io/t/userwarning-attempted-to-set-unknown-attribute-location-on-instance-of-container/22421/4
- https://github.com/meteor/meteor-feature-requests/issues/389 

I don't know why this happens.

**Comment by xet7** [comment]
Ok I fixed it, it was just missing backtick quotes in code. Strings values like regex text should be surrounded with quotes.

**Comment by jrsupplee** [comment]
> Ok I fixed it, it was just missing backtick quotes in code. Strings values like regex text should be surrounded with quotes.

This has broken the search.  The backticks are not needed.

**Comment by jrsupplee** [comment]
> @jrsupplee
> 
> It seems building Snap fails because of https://github.com/wekan/wekan/blob/master/client/components/main/globalSearch.js#L484 , see https://forum.snapcraft.io/t/userwarning-attempted-to-set-unknown-attribute-location-on-instance-of-container/22421 .
> 
> Could that code be changed to not use text `location` ?

The location code is not new.  The snap built with it before.  It, of course, can be rewritten to not use `window.location`

**Comment by jrsupplee** [comment]
@xet7 

Could it be a Javascript version problem with the snap build?  I am using Unicode classes in the RegExp (which is new).

**Comment by jrsupplee** [comment]
These two commits, broke the RegExps:
* bf7b1789ec16e3c52397318c799ec5a0fc2de3a5
* 0ff215f78f03c81d153dfc0ffa08fac94b542ec2

**Pull request merged**
