### PR TITLE
Update ukrainian translation

### PR DESCRIPTION
**Pull request by novashdima**
- Remove deleted ua_UA, ua
- Remove invalid ru_UA
- Update uk-UA, uk

### CODE REVIEW

**Comment by xet7** [comment]
@novashdima

Translations are done at https://app.transifex.com/wekan/wekan , not as pull requests.

Only, when adding new features, new strings are added to en.i18n.json as pull request.

**Comment by zpoken** [comment]
@xet7 ok
and how to remove obsolete and invalid translations?

**Comment by novashdima** [comment]
@xet7 ok
and how to remove obsolete and invalid translations?

**Comment by xet7** [comment]
@novashdima 

In what way they are obsolete or invalid?

**Comment by xet7** [comment]
@novashdima

Those language options exist at Transifex. Sometime, someone has added translations for some languages. I don't usually remove translations, because I don't know what people whre speak that language. I don't know can any language become obsolete.

**Comment by novashdima** [comment]
@xet7 

The current name for the Ukrainian language in the iso is uk_UA (Ukraine Ukrainian), ua_UA and ru_UA are old names for the Ukrainian language.
Also, the translation files ua and ua_UA have been deleted, but they exist in the configuration. Therefore, I see 5 Ukrainian languages in the application, of which ua and ua_UA cannot be selected because there are no localization files, ru_UA is an outdated name for Ukrainian, and the localization file is in Russian.

uk and uk_UA are the correct names for Ukrainian, they should be left, I will update them via the app you threw down.

**Comment by xet7** [comment]
Hmm, just a moment, I try to update Transifex directly.

**Comment by novashdima** [comment]
@xet7

I already update most of the lines manually

**Comment by click0** [comment]
> uk and uk_UA are the correct names for Ukrainian, they should be left,
@xet7

As the transifex.com service doesn't support creating language aliases, it might be best to keep only the uk_UA version.
Please remove the `Ukrainian (uk)` and `Russian (Ukraine) (ru_UA)` language versions.

**Pull request closed without merging**
