### PR TITLE
Development in docker container

### PR DESCRIPTION
**Pull request by mfilser**
Development in Docker Container

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3852)

### CODE REVIEW

**Comment by xet7** [comment]
@mfilser 

I will check is there newer base image, and copy it from Docker Hub to Quay. Base images are at Quay, because Docker Hub has rate limits. I have applied to Docker Hub Open Source developer program, but I have not received reply yet.

**Comment by mfilser** [comment]
@xet7
I didn't change the base image of the main Dockerfile, just for development (subdirectory. devcontainer). Development is normally not security relevant i think, it's mostly running at localhost.

But i can test it with the same image, so Dockerfile and. devcontainer/Dockerfile have the same base image.

What do you think?

**Comment by mfilser** [comment]
I changed it. I will rebuild and push the new commit on success.
I think it's better to have the same base image in development and productive environment

**Comment by xet7** [comment]
@mfilser 

Please use newest ubuntu hirsute base image from Wekan repo latest commit.

**Comment by mfilser** [comment]
GPG error with this image at commad apt-get update.

I will send the error message when i am at the PC again (currently using my good old netbook and mobile 😁)

**Comment by xet7** [comment]
Hmm, I'll test does that ubuntu hirsute docker image work.

**Comment by mfilser** [comment]
Great. Do you test the main, the development or both?

**Comment by xet7** [comment]
Both

**Comment by xet7** [comment]
@mfilser 

Actually, building wekan/Dockerfile with hirsute does fail, because of this error:
```
GPG error: http://security.ubuntu.com/ubuntu hirsute-security InRelease: gpgv, gpgv2 or gpgv1 required for verification, but neither seems installed E:
10.6.2021 klo 21.20.50 The repository 'http://security.ubuntu.com/ubuntu hirsute-security InRelease' is not signed. 
```
So it seems gpg is not installed. Just a moment I try to add it to required packages.

**Comment by xet7** [comment]
Usually when changing base image to newer version of Ubuntu, some package names are different, so I update Dockerfile etc.

**Comment by xet7** [comment]
Doh, it's a bug:
https://stackoverflow.com/questions/66319610/gpg-error-in-ubuntu-21-04-after-second-apt-get-update-during-docker-build

Sorry, I'll revert updating base image to hirsute.

**Comment by xet7** [comment]
I'll test this more sometime tomorrow or after that.

**Comment by mfilser** [comment]
@xet7 
Building now works at the dev container

**Pull request merged**
