### PR TITLE
added padding

### LINKED ISSUE #3558: No padding between logo and Text in header
In the latest version there is no space between the logo and the text.

image

### PR DESCRIPTION
**Pull request by lindhork**
Fixes #3558 

image

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3559)

### CODE REVIEW

**Comment by mfilser** [comment]
@lindhork 
Did you also check the mobile view how it looks there?
In the end it breaks the mobile view, especially if there are many favorite boards at the quick access.

**Comment by lindhork** [comment]
Hey @mfilser,
I checked the mobile view, on an ipad pro it looks ok, on smaller devices the logo and text is not shown anyway.

grafik
grafik

I don't understand your argument why it breaks the mobile view? I have only edited the case when no board is favorited, the behavior when you have favorited boards has not changed.
You still get a long list in which you can scroll left and right.

grafik

**Comment by mfilser** [comment]
@lindhork 
I was just thinking about it (because i did there some changes a few weeks ago) and didn't check it on my dev system.
Thank you for checking this and the screenshot's :)

**Comment by lindhork** [comment]
@mfilser 
What do you think about moving the house a bit to the right for small devices, so that it doesn't stick directly to the edge?

grafik

**Comment by mfilser** [comment]
@lindhork
I think this will be a good solution 👍
Thank you for mention it.

**Pull request merged**
