### PR TITLE
Includes possibility to block username change

### PR DESCRIPTION
**Pull request by thiagofernando**
I created an option that blocks the user from being able to change the username. Similar to email´s change blocking.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1627)

### CODE REVIEW

**Comment by xet7** [comment]
@thiagofernando 

Remove translation changes to other than `i18n/en.i18n.json`, see https://github.com/wekan/wekan/pull/1470#issuecomment-364171034

**Comment by thiagofernando** [comment]
Done!

**Comment by xet7** [comment]
How this works?

I don't see "Allow Username Change" option in Admin Panel / Settings / Accounts, in file
wekan/client/components/settings/settingBody.jade

Did I build it wrong? Or is there such option?

**Comment by thiagofernando** [comment]
sorry, my mistake. i forgot to send the file.

**Pull request merged**
