### PR TITLE
Set the card color with the color picker

### PR DESCRIPTION
**Pull request by bentiss**
When triggered from the hamburger.

After a lot of tries and errors, I finally got the color picker working.

I figured out it would be better than setting the per-dropdown item background as in the end, we don't really want the end user to exactly know which color is which.

There is still the issue of the color with the IFTTT, but I don't know if we can have a color picker there as well.

Note: Apache: I-CLA signed

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2117)

### CODE REVIEW

**Comment by xet7** [comment]
@bentiss 

I'm currently looking at changing IFTTT Rules color names to colors.

**Comment by bentiss** [comment]
> You can do git pull on edge branch. I did change IFTTT Rules dropdown colors to translated text with dropdown having both text and color.

Sounds good. However, Firefox 64 doesn't seem to appreciate the background color per item. They all stay white.

> But maybe that dropdown button itself could have color applied also, that way text would not need to be there.

Having some feedback on the chosen color would be nice, indeed. Maybe we can just use the color picker in the IFTTT case too, and make the button changing color depending on the selected color.

**Comment by xet7** [comment]
@bentiss 

> Having some feedback on the chosen color would be nice, indeed. Maybe we can just use the color picker in the IFTTT case too, and make the button changing color depending on the selected color.

That would be nice. Can you try to get it working?

**Comment by bentiss** [comment]
@xet7 
I'll try to have a look.

**Comment by bentiss** [comment]
I realized there was a bug in the translated colors for the labels. Please see #2119

**Pull request merged**
