### PR TITLE
New feature - Optional board list auto-width, Support for min & max width for lists

### PR DESCRIPTION
**Pull request by NadavTasher**
This feature comes as a solution for issue https://github.com/wekan/wekan/issues/5593.

This PR introduces changes to allow for optional automatic widths for all lists in a board.
It also adds support for minimum and maximum width for each list (in pixels).

A new toggle was added:
image
image

When auto-width is enabled, lists will try to expand to fill the size of the screen, as demonstrated here:
image

When there are too many lists and this feature is enabled, the lists will just add up, each list taking just the `min-width` as defined in the `Set Widths` popup:
image

Here's how the new `Set Widths` popup looks (note that the values in the screenshot are not the defaults):
image

Please thoroughly review the changes in this PR before merging.

### CODE REVIEW

**Comment by mfilser** [comment]
@NadavTasher
is it possible to use functions from the Util class, e. g. this one?
https://github.com/wekan/wekan/blob/a3f70735ac174ac6c1c37008680e30312bf7fdbc/client/lib/utils.js#L44

**Comment by NadavTasher** [comment]
> @NadavTasher is it possible to use functions from the Util class, e. g. this one?
> 
> https://github.com/wekan/wekan/blob/a3f70735ac174ac6c1c37008680e30312bf7fdbc/client/lib/utils.js#L44

@mfilser 
`Utils.getCurrentBoardId()` seems like a better fit here.
I have pushed a commit that uses it.
Thanks!

**Comment by mfilser** [comment]
I think in the last commit you changed to Utils: It's good to get the boardId from the list data.

My thought was more to replace the other parts of Session.get with the Utils class.

Sorry, I am on my mobile right now, so I can't write well.

**Comment by NadavTasher** [comment]
Oh I see.
I have reverted that change and updated the code in `boardHeader.js` to use the aforementioned utility function.

I only used `Session.get` because it was used in the line above (I just copied it)

**Comment by mfilser** [comment]
I see. Sometimes that deprecated code comes in.
To use the Utils function is necessary for the mobile version.

Could you change this too?

const boardId = Session.get('currentBoard');

**Comment by NadavTasher** [comment]
I see I forgot to commit this change.
Done. 😄

**Comment by mfilser** [comment]
Great, thank you very much, and also for your contribution.
I didn't have the time to try and test, I hope I can do it soon...

**Pull request merged**
