### PR TITLE
Dockerfile fix for local packages (Take 2)

### PR DESCRIPTION
**Pull request by Serubin**
**This hasn't been tested, I don't have a way to test this currently** 

Can someone please confirm that this works as expected BEFORE being merged in?

This should fix the local flow-router dependency.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/959)

### CODE REVIEW

**Comment by stephenmoloney** [comment]
As previously discussed, you cannot run the command `source` like that inside a dockerfile.

This will not work.

https://travis-ci.org/wekan/wekan#L4565

**Comment by Serubin** [comment]
@stephenmoloney Can you please offer a suggestion on an alternative way to add an environment variable?

**Comment by stephenmoloney** [comment]
@Serubin 
I did [in this post](https://github.com/wekan/wekan/issues/928#issuecomment-289859392)

I even tried those changes for the `ENV`

It doesn't work. 

I would focus on https://github.com/wekan/wekan/pull/957 for now to get the Dockerfile up and running.

**Comment by Serubin** [comment]
I see what's going on now. Have we looked into options like this? https://github.com/npm/npm/issues/9863

**Comment by stephenmoloney** [comment]
The closest issue is documented [here](https://github.com/wekan/wekan/issues/928#issuecomment-289714017)

We need to upgrade meteor, various dependencies and node js.

That is ongoing now at #957

**Comment by Serubin** [comment]
Understood.

**Pull request closed without merging**
