### PR TITLE
Added clearblue theme

### PR DESCRIPTION
**Pull request by CidKramer**
I wanted a theme which changed the color of the board's background aswell as the header. 

The theme uses transparent elements for the swim lanes and cards. The color option "clearblue" is added as an example but any desired color be created using the `setBoardClear(color1,color2)` function in **boardColors.styl**.

wekan_clearblue_20200515

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3093)

### CODE REVIEW

**Comment by xet7** [comment]
@CidKramer 

There is some bug, your changes disables the ability to change Swimlane Color and Card Color in all themes.

**Comment by CidKramer** [comment]
Hmm, I was not able to replicate that. I did notice one problem with my theme though is the text doesn't change to white when you select an alternate card color.

**Comment by xet7** [comment]
@CidKramer 

For me, there those change color popups did not have any colors listed at all.

**Comment by CidKramer** [comment]
This is the behavior I am seeing:
card_color_1

card_color_2

I'm clicking the three bars, and selecting "Set color" on the swimlane and card respectively. In both cases I get a selection of colors to choose from:
card_color_3

**Comment by xet7** [comment]
Ok, I will test again.

**Pull request merged**
