### PR TITLE
Add Feature: User can have richer formatted text into the comments

### PR DESCRIPTION
**Pull request by whowillcare**
User can write/edit formatted comments including table contents, or pasted in an HTML snippet (will be sanitized) to the comment. 

App owner can disable this feautre by setting 

METEOR_SETTINGS='{"public":{"NO_RICHER_EDITOR":false}}'

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2560)

### CODE REVIEW

**Comment by xet7** [comment]
@whowillcare 

With your pull request, labels don't show correctly:

labels-broken

And language names are visible in only half:

languages-broken

**Comment by xet7** [comment]
What would happen to description field if you add this formatted text field there? would it convert existing description markdown to be visible correctly?

Background colors have also moved to left. Maybe some CSS change affects all those menus? Thanks!

background-colors-broken

**Comment by xet7** [comment]
At `All Boards` page, board bottom hover icons for archiving and duplicating board are not fully visible:

board-hover-buttons-are-not-visible

**Comment by whowillcare** [comment]
I'll take a look, it could be the css changes I made, but it should only affect mobile client. thx. will update you with what I've found. and Fix them to what it should be. 
thanks

**Comment by xet7** [comment]
As summary, these are moved to left:

### Card hamburger menu

- [ ] Edit Custom Fields
- [ ]  Change Spent Time
- [ ]  Set Color
- [ ]  Move Card
- [ ]  Copy Card
- [ ]  Copy Checklist Template to Many Cards,
- [ ]  More

### Swimlanes hamburger menu on Board

- [ ] Set Color
- [ ] Set WIP Limit
- [ ] More

### Swimlanes hamburger menu on Templates

- [ ] Set Color

### Board click top right username menu

- [ ] Edit Profile
- [ ] Change Settings
- [ ] Change Avatar
- [ ] Change Password
- [ ] Change Language

## Board hamburger menu / cog settings button at right side of members

- [ ] Change Color
- [ ] Export Board - this goes to `All Boards` page, and does not give exported JSON file.
- [ ] Move Board to Archive
- [ ] Outgoing Webhooks
- [ ] Subtasks Settings

## All Boards page

- [ ] Add Board / Import
- [ ] Add Board / Template

**Comment by xet7** [comment]
I think richer text should work the same on both mobile and desktop mode.

**Comment by whowillcare** [comment]
it might be related to newly introduced module of bootstrap, because summernote needs that. I will dig more.

**Comment by xet7** [comment]
That boostrap maybe did bring this strange checkbox style change to Yes/No checkboxes?

checkbox-style-change

**Comment by xet7** [comment]
Looks like user initials avatars is now smaller?

initials-avatar-small

**Comment by whowillcare** [comment]
@xet7 
Found the problem, the introduced bootstrap.css is indeed the culprit. I have added a solution by adding an overriding global style to * in main/layouts.styl file, it looks alright to me now. Please verify. thanks.

**Comment by xet7** [comment]
Did boostrap add grey around minicard comment icon and number of comments? And grey around description icon on minicard? It should be removed.

On most themes:

comment-grey-1

On relax theme even stranger:

relax-comment-grey

**Comment by xet7** [comment]
Also seems that boostrap did add blue underline hover to every clickable element, like here Description, it's also visible at Due Dates, checklists etc when hovering mouse over those. It should be removed.

hover-underline-blue-not-needed

**Comment by xet7** [comment]
> App owner can disable this feautre by setting
> METEOR_SETTINGS='{"public":{"NO_RICHER_EDITOR":false}}'

That is double negative. It should be changed to these simpler settings:
```
RICHER_EDITOR=true
RICHER_EDITOR=false
```

**Comment by xet7** [comment]
Those strange checkbox changes still exist that I mentioned here https://github.com/wekan/wekan/pull/2560#issuecomment-514217098

**Comment by whowillcare** [comment]
k. I will double check the checkbox, fix it and let you know. thx

**Comment by whowillcare** [comment]
Problem found, wekan admin panel has a class form-control in settingsBody.jade and settings.styl, but settings.styl didn't really define the normal appearance but used default style, while this class just collided with bootstrap 4 css, either a coincidence or original author was a Bootstrap fan. :) anyway, I renamed the class name from form-control to wekan-form-control. Problem has fixed, and I also made some other slight changes and pushed. thanks

**Comment by xet7** [comment]
Currently these are not fixed yet:

- [ ] [Removing grey background of minicard elements](https://github.com/wekan/wekan/pull/2560#issuecomment-514542347)
- [ ] [Removing blue link hover](https://github.com/wekan/wekan/pull/2560#issuecomment-514548085)
- [ ] [Renaming environment variable](https://github.com/wekan/wekan/pull/2560#issuecomment-514550992)

**Comment by whowillcare** [comment]
@xet7 
Sorry for the delay, finally got sometime today, and was able to the last three items you have identified. basically, I changed the environment variable, put the unset values for .badge, a:hover, a:focus into layouts.style to override the conflicting css settings with bootstrap, then it appears normal and OK to me now. 

cheers

**Comment by saschafoerster** [comment]
Somehow I can't disable the Rich Text Editor in Docker-Compose, which is annoying. The rich-text-editor is missing mentions for example, which is important in comments. I actually would prefer to have the rich text editor in the description field instead.

**Pull request merged**
