### PR TITLE
Due and start date for cards

### PR DESCRIPTION
**Pull request by shoetten**
Hey,

i added start and due date functionality to cards. Since i'm fairly new to meteor, any comments are highly appreciated.

Several things still need some work, but i'm not sure how to this in the most appropriate way:
- Localization for the date picker. I used [bootstrap datepicker](https://github.com/eternicode/bootstrap-datepicker) which comes with [locales](https://github.com/eternicode/bootstrap-datepicker/tree/master/js/locales), but i'm not sure how to include them best.
- Hook into the wekan activities / notifications feed. A reminder message e.g. 2 days before an assigned card expires would be awesome..
- Make the moment locale change reactively, so the date format changes when the user selects a new language.

Also, i would suggest putting the badges before the members in the minicards, but since that's more of an aesthetic opinion, i did not include it in this pull request.

Thanks for all suggestions!

[Review on Reviewable](https://reviewable.io/reviews/wekan/wekan/517)

### CODE REVIEW

**Comment by mquandalle** [comment]
Thank you, I will review shortly and address your three questions

**Comment by thihy** [comment]
+1

**Comment by irfanitw** [comment]
@mquandalle All is good here?

**Comment by Abioy** [comment]
wonderful! how is it going?

**Comment by theSoenke** [comment]
Any status for this? Would be a really useful feature for me

**Pull request closed without merging**
