### PR TITLE
Fixed advanced filter description.

### PR DESCRIPTION
**Pull request by zypA13510**
The syntax in advanced filter description is wrong (assignment operator = instead of equality comparison operator ==).

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1710)

### CODE REVIEW

**Comment by zypA13510** [comment]
@xet7 Someone please review this?

**Comment by xet7** [comment]
@zypA13510 

I need to add these changes manually to every translation myself sometime, because otherwise every translator needs to translate this again.

**Comment by zypA13510** [comment]
@xet7 then should I just change = -> == in every language?

**Comment by xet7** [comment]
@zypA13510 

It's better that I do it, because only I can change base english language etc.

**Pull request merged**
