### PR TITLE
Fonts 2bis

### PR DESCRIPTION
**Pull request by johnleeming**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1579)

### CODE REVIEW

**Comment by johnleeming** [comment]
sorry error

**Comment by xet7** [comment]
@johnleeming 

What you tried to add? I can not add any MS fonts to Wekan. Wekan uses free Roboto font.

**Comment by johnleeming** [comment]
Personally I find the roboto font too thin.  Our corporate font is Trebuchet and I was playing around trying to use it when I pulled against the wrong branch - sorry.  Please delete this PR

**Comment by xet7** [comment]
@johnleeming 

It's not possible for me to delete pull requests, see:
https://stackoverflow.com/questions/18318097/delete-a-closed-pull-request-from-github

AFAIK this pull request does not contain any sensitive data.

**Pull request closed without merging**
