### PR TITLE
add more label colors https://github.com/wekan/wekan/issues/457

### PR DESCRIPTION
**Pull request by JamesLavin**
Adding new label colors (see: https://github.com/wekan/wekan/issues/457)

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1412)

### CODE REVIEW

**Comment by xet7** [comment]
@JamesLavin 

When copying/moving card, or import/export of wekan board, new label colors are not included.

Directory structure: https://github.com/wekan/wekan/wiki/Directory-Structure

Move/Copy card: https://github.com/wekan/wekan/pull/1330

**Comment by killua-eu** [comment]
Hey @xet7, do you think that the new colours not being included is just this https://github.com/wekan/wekan/blob/a48630ffcfa5a5d96afad5960875da6e856ac079/models/boards.js#L103 piece of code missing the names? I searched the codebase for the 'yellow' string, except for the already changed files (and translations), this was the only place that seemed to explicitly name the colours. If this solves the issues you described, I'll patch that.

**Comment by xet7** [comment]
@killua-eu 

Yes you could try patching that. I can then try pull request again.

**Comment by rjevnikar** [comment]
what is left to be done on this PR before it can be included?
I have a request from a user to add more label colours, so am happy to try and get this working

**Comment by xet7** [comment]
@rjevnikar 

I did reply to @JamesLavin above:
> When copying/moving card, or import/export of wekan board, new label colors are not included.

See:
* [Import](https://github.com/wekan/wekan/blob/devel/models/import.js)
* [Import Wekan board](https://github.com/wekan/wekan/blob/devel/models/wekanCreator.js)
* [Export Wekan board](https://github.com/wekan/wekan/blob/devel/models/export.js)
* [Migrations](https://github.com/wekan/wekan/blob/devel/server/migrations.js)
* [Componets like labels etc](https://github.com/wekan/wekan/tree/devel/client/components)

Wekan core really is well organized and easy to modify. I recommend just reading that code and trying modifications. Also see [Developer Docs](https://github.com/wekan/wekan/wiki/Developer-Documentation).

**Comment by xet7** [comment]
Already merged at https://github.com/wekan/wekan/pull/1679 and released in Wekan v1.03 today :)

**Pull request closed without merging**
