### PR TITLE
Added new function to add cumstom translation strings on Admin panel

### PR DESCRIPTION
**Pull request by ipyramiddev**
Hello @xet7, I've added the new function to add custom translation strings as you recommended in issue #5065.
Please check it and merge it.
Regards,
Yevhenii

### CODE REVIEW

**Comment by xet7** [comment]
Docs at https://github.com/wekan/wekan/wiki/Customize-Translations

**Comment by xet7** [comment]
@ipyramiddev 

Please create new PR where you make these changes to your code, so that it works correctly with reactiveCache:

https://github.com/wekan/wekan/issues/5000#issuecomment-1640950446

**Comment by mfilser** [comment]
@ipyramiddev 
I thought Translations are working on the client side too, but on my tests, it fails.
Did the translations work on the client side for you?

**Comment by mfilser** [comment]
@ipyramiddev 
Never mind, i think I found the solution.

**Comment by xet7** [comment]
@mfilser 

Translations did work before this reactiveCache fix, that broke it https://github.com/wekan/wekan/pull/5087

**Comment by mfilser** [comment]
@xet7 
I will send PR to get it working again.

**Pull request merged**
