### PR TITLE
Add Feature: Board templates or other stuff

### PR DESCRIPTION
**Pull request by floatinghotpot**
clone board template from another board to current board, including members, labels, and lists, thus a new board can be quickly setup.

[Review on Reviewable](https://reviewable.io/reviews/wekan/wekan/446)

### CODE REVIEW

**Comment by mquandalle** [comment]
Generally speaking I would remove the notion of a “board template” from the code base in favor of simpler “clone” feature, I exposed this idea in https://github.com/wekan/wekan/issues/308#issuecomment-141135503.

I’m also experimenting (for the first time with this PR) with a new code review application. It has happen a few time that I put a comment on a GitHub PR, and then the code change so GitHub hide the comment whereas it’s still not addressed. So we will see if Reviewable.io improve thing or not, feel free to comment if you have an opinion on this :-)

---

Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[client/components/boards/boardHeader.jade, line 85 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zoUDyt-AfX-fBVqSV:-K5zoUDzWZYA9peTQwdQ:970388046) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/client/components/boards/boardHeader.jade#L85)):*
Not saying this is fundamentally better but you can avoid the creation of a custom helper here by using `($.Session.equals 'currentBoard' _id) which is provided by [raix:handlebar-helpers](https://github.com/raix/Meteor-handlebar-helpers).

Anyway this whole class of issues will disappear with the soon to come migration to React.

---

*[client/components/boards/boardHeader.js, line 218 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zpCC7ZtODNFTciV5q:-K5zpCC7ZtODNFTciV5r:-1226266546) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/client/components/boards/boardHeader.js#L218)):*
Hum, why do you have to use that? Isn’t something like `this.currentData()._id.trim()` supposed to work?

---

*[models/boards.js, line 347 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zph9tl0Ht_8gtZCTE:-K5zph9tl0Ht_8gtZCTF:-1670061724) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L347)):*
I guess if the board is public you don’t need to be a member to clone it. We should abstract this condition somewhere, IIRC it’s already duplicated in two places (the publication function, and the export generation).

---

*[models/boards.js, line 399 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zqK_acpDGoFcbPsfl:-K5zqK_acpDGoFcbPsfm:2067182094) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L399)):*
As it is still possible to restore them, maybe we should copy archived lists as well?

---

*[models/boards.js, line 406 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zr-TMyY7oH1IUfmEu:-K5zr-TMyY7oH1IUfmEv:1486117464) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L406)):*
This is a bit weird to me, and sounds a bit error prone. Is this just some optimization or is there a deeper rationale?

---

*[models/boards.js, line 411 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zqizi7rGV1KVG6q6Q:-K5zqizi7rGV1KVG6q6R:-291552784) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L411)):*
Do we need a `$set` here? If we want to just replace the entire document we can use `.update(selector, newDocument)`

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446#-:-K5zrjxHeLwFrVXuVMB4:798451853)*

**Comment by mquandalle** [comment]
On the review process, I don’t really like the default way of batching all the comments in a single message, will see if I can configure so that it interfaces with GitHub inline comments.

**Comment by floatinghotpot** [comment]
*[models/boards.js, line 411 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zqizi7rGV1KVG6q6Q:-K6-EFExZyaFJCPa8fd5:-1502432741) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L411)):*
The document are not replaced entirely. At least, the _id won't be changed, especially if there are some cards, the listId should not be changed.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by mquandalle** [comment]
Reviewed 1 of 4 files at r1, 1 of 2 files at r2.
Review status: 3 of 4 files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
This review tool is not bad. Have a try. :-)

You are correct, cloning a empty board is importing template. 

Will it be over-engineering if clone all cards (and attachments, comments)? My own use case is to setup a new board, and the needs in #308 discussion seems same. 

And, a possible use case is, there are already some cards on current board, and user may wanna keep them, but apply template only.

Should give user the option to select what to clone: members, labels, lists, cards, attachments, comments?

---







*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446#-:-K6-8zfupMlnlTbCpj15:-1725167209)*

**Comment by mquandalle** [comment]
Review status: 3 of 4 files reviewed at latest revision, 5 unresolved discussions.

---

*[client/components/boards/boardHeader.jade, line 88 \[r2\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K6-RaiI_jDAvN0KWx7h:-K6-RaiJPdHHQzJJdVwj:-330601174) ([raw file](https://github.com/wekan/wekan/blob/42d71c7fb5886271ffb9c89b70d879cb7517b256/client/components/boards/boardHeader.jade#L88)):*
The `id=` argument isn’t needed anymore.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[client/components/boards/boardHeader.jade, line 85 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zoUDyt-AfX-fBVqSV:-K6-BBU-95b3g1_njs8i:1702964948) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/client/components/boards/boardHeader.jade#L85)):*
I had a try to use it, but encountered a error:
Error: Can't call non-function: undefined
    at Spacebars.call (spacebars-runtime.js:136)
    at Spacebars.mustacheImpl (spacebars-runtime.js:70)
    at Object.Spacebars.dataMustache (spacebars-runtime.js:102)
    at boardHeader.jade.js:319

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[client/components/boards/boardHeader.js, line 218 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zpCC7ZtODNFTciV5q:-K6-Q8hAvpC2UZFpSqte:535844731) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/client/components/boards/boardHeader.js#L218)):*
Ok, yes, it works.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[models/boards.js, line 347 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zph9tl0Ht_8gtZCTE:-K6-PrxHCerOE1gPFHmE:-760882840) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L347)):*
Ok. Only check private board now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[models/boards.js, line 399 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zqK_acpDGoFcbPsfl:-K6-IIIQMWmJ0_WUrs6r:859961180) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L399)):*
Ok. Also copy archived lists now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[models/boards.js, line 406 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zr-TMyY7oH1IUfmEu:-K6-DribFhlpAQqVzxOq:320881237) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/models/boards.js#L406)):*
The current board may have existing lists. And, they may even have cards on them. So need keep the lists, but copy the titles only.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by mquandalle** [comment]
Review status: 3 of 4 files reviewed at latest revision, 6 unresolved discussions.

---

*[client/components/boards/boardHeader.jade, line 85 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zoUDyt-AfX-fBVqSV:-K6-SQskyGwH6WDxLJzZ:673172667) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/client/components/boards/boardHeader.jade#L85)):*
Ok I’m a bit surprised but that’s not important. Let’s keep it like what you have done (again, this will be re-factored with React anyway). 

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[client/components/boards/boardHeader.jade, line 88 \[r2\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K6-RaiI_jDAvN0KWx7h:-K6-T5XrK8UG2FEqYWSp:-499146009) ([raw file](https://github.com/wekan/wekan/blob/42d71c7fb5886271ffb9c89b70d879cb7517b256/client/components/boards/boardHeader.jade#L88)):*
Done.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by floatinghotpot** [comment]
*[client/components/boards/boardHeader.jade, line 85 \[r1\]](https://reviewable.io:443/reviews/wekan/wekan/446#-K5zoUDyt-AfX-fBVqSV:-K6-T3zBAG25q0_Puq3a:160384653) ([raw file](https://github.com/wekan/wekan/blob/24b9ce0ae17cda26ead967f7bb6cda258c11c337/client/components/boards/boardHeader.jade#L85)):*
Ok.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by mquandalle** [comment]
Reviewed 1 of 1 files at r3.
Review status: 3 of 4 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/wekan/wekan/446)*

**Comment by nata-g** [comment]
@mquandalle  Is this going to be merged? I though the code review is already done?

**Comment by mquandalle** [comment]
So first of all I have to apologize to @floatinghotpot because I did the code review before actually running the code on my machine as I was excited to test Reviewable (I’m happy with it BTW, it allows me to keep track of sub issues in a better way and supper git rebasing). So I actually misunderstood this feature as being a “full clone” feature whereas it is actually a way to re-use a board template (similar to what is discussed in #308). This doesn’t change much in my review, just the fact that not copying archived lists as you originally did @floatinghotpot, was actually making sense.

Also I feel like the UX is not intuitive, because you first have to create a board and then go in the board menu to “Import template” (and if you already have some data in the board the UI will alert you that the board structure will be overwritten, “This action will overwrite current members, labels and lists.”). I think this feature makes much more sense as an option in the creation form:

Create Board popup

I’m not sure about the actual UI, I just modified the HTML in the browser tool to share the idea that the template should be defined on the board instantiation, not by overwriting any structure at a latter time.

Also I would really like this feature to be implemented as a plugin, maybe installed and activated by default, but the plugin work will rely on Meteor 1.3 that is currently not working with Wekan. Hopefully MDG will release a new beta this week so I can start writing a `0.1` version of the module system and API. If I can’t get that minimal version implemented in any reasonable delay, then I will merge this feature without the ideal modularity and that will come later.

**Comment by floatinghotpot** [comment]
Yes, I thought of adding it when creating a new board, but did it in current ugly way in a hurry for our project needs.

I will wait your plugin system ready, then re-write it.

**Comment by irfanitw** [comment]
@mquandalle @floatinghotpot, this is a great feature! What do we need to get this thru?

**Comment by FrDu** [comment]
How is the status of this project ?
Is there a time frame for to be added into a main release ?

**Comment by xet7** [comment]
Related #979 and #797

**Comment by GregBusch1995** [comment]
Status?

**Comment by xet7** [comment]
@GregBusch1995 

This old PR is not related to current Template issue #2165 that is not merged yet. Template issue will be added to stable release when it works.

**Comment by xet7** [comment]
@GregBusch1995 

Wekan v2.29 is now released, it includes current Templates feature that is in progress. If you find some new bugs, please add comment to #2165

**Comment by justinr1234** [comment]
@xet7 is this one still relevant?

**Comment by xet7** [comment]
@justinr1234 

No, Wekan already has board templates.

**Pull request closed without merging**
