### PR TITLE
add console, file, and zulip logger on database changes

### PR DESCRIPTION
**Pull request by huneau**
hi there,

Related here: #1001 

I create a logging mechanism using winstonjs.

The supported log is console, file, and zulip, up to you if you want more.

Actually, only JSON is supported as output.

Possible output 
```
{"userId":"7gLzSQYeLadyScLb4","type":"card","method":"update","doc":{"_id":"DvwygsfayN2KTSFjt","title":"regezrg","members":[],"labelIds":[],"listId":"kFApw5GrTRSwc86BZ","boardId":"ZeEpvQXNfKG2BDoFD","sort":6,"archived":false,"createdAt":"2017-04-14T13:09:56.617Z","dateLastActivity":"2017-04-19T13:51:30.937Z","userId":"7gLzSQYeLadyScLb4"},"fieldNames":["listId","sort","dateLastActivity"],"modifier":{"$set":{"listId":"th5sg8cYSBzB4Qm3J","sort":6,"dateLastActivity":"2017-04-19T13:57:18.579Z"}},"timestamp":"2017-04-19T13:57:18.581Z","message":"","level":"info"}
```
This one is when a card is moved.

Only database changes are logged.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1010)

### CODE REVIEW

**Comment by huneau** [comment]
I have signed the license, why they won't validate it.

**Comment by xet7** [comment]
@huneau 

Please provide commands you used:

- installing all dependencies like node.js etc
- starting wekan.

I did not get it working yet, so probably I used wrong versions etc.

**Comment by huneau** [comment]
Hi, 

I do nothing important, 
- dependencies
  - npm install winston
  - mpn install winston-zulip

- meteor to run without any other options

**Comment by xet7** [comment]
@huneau 

I need all steps of cloning repo, installing node.js version, and versions of other dependencies to reproduce working version of wekan. In addition, how do I test your feature and see how it works? What menu options are new, does it integrate with something, commands to use to test it, etc.

**Comment by huneau** [comment]
> I need all steps of cloning repo, installing node.js version, and versions of other dependencies to reproduce working version of wekan.

``` shell
git clone https://github.com/huneau/wekan.git
cd wekan/
git checkout meteor-1.4-LOGGER

### for the rest nothing change 

sudo npm -g install npm@latest
sudo npm -g install node-gyp
sudo npm -g install fibers

npm install

meteor
 ```

I have added a few environment variable : 
```shell
export LOGGER_ENABLE=< true || false >

## LOGGERS => list of logger type, concatenate with a comma 
## actually supported 'console', 'file','zulip' (zulip is my use case)
export LOGGERS=console,file

## For Console nothing any settings needed

## For File 
## File will be create logs/<filename>
export LOGGER_FILE_NAME=<file name>

## For Zulip
export LOGGER_ZULIP_USERNAME=<zulip username>
export LOGGER_ZULIP_APIKEY=<zulip apikey>
export LOGGER_ZULIP_REALM=<zulip host>
export LOGGER_ZULIP_TO=<stream>
export LOGGER_ZULIP_SUBJECT=<stream topic>
```
I think that's it.

>  how do I test your feature and see how it works?

For console
```shell
export LOGGER_ENABLE=true
export LOGGERS=console
```

For file
```shell
export LOGGER_ENABLE=true
export LOGGERS=file
export LOGGER_FILE_NAME=server.log #create if not exist
```

For both
```shell
export LOGGER_ENABLE=true
export LOGGERS=console,file
export LOGGER_FILE_NAME=server.log #create if not exist
```

For zulip is a bit more complex
Project : https://github.com/galexrt/docker-zulip
```shell
##WEKAN CONF
export LOGGER_ENABLE=true
export LOGGERS=zulip
export LOGGER_ZULIP_USERNAME=<zulip username>
export LOGGER_ZULIP_APIKEY=<zulip apikey>
export LOGGER_ZULIP_REALM=<zulip host>
export LOGGER_ZULIP_TO=<stream>
export LOGGER_ZULIP_SUBJECT=<stream topic>

#####################################

## ZULIP INSTALLATION
git clone https://github.com/galexrt/docker-zulip.git
cd docker-zulip/
## replace SETTINGS_* variables
vi docker-compose.yml
docker-compose up -d
##after is a zulip webapp config for bot and apikey etc etc
```

> What menu options are new?

Any menu has been changed.

> does it integrate with something?

I use Zulip here, but if you don't call it in environment variable you need nothing else.

> commands to use to test it ?

Nothing, just plays with wekan and you will see logs appear where you have specified them.


If you need more, just ask and I will try to respond quickly as possible.
Thinks.

**Comment by xet7** [comment]
@huneau 

What node version are you using?

**Pull request merged**
