### PR TITLE
Update sl.i18n.json

### PR DESCRIPTION
**Pull request by jernejh**
Updated strings mostly by Vasja K.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2734)

### CODE REVIEW

**Comment by xet7** [comment]
Next time, please translate at https://transifex.com/wekan/wekan/   . Thanks!

**Comment by jhgovsi** [comment]
i actually did translate on transifex, but i did not know, that it is possible to start a pull request over transifex...

**Comment by xet7** [comment]
@jhgovsi 

Translating at Transifex is enough. I do often download all translations at once from Transifex and add them to Wekan. There is no need to do pull request.

**Comment by jhgovsi** [comment]
Ok, noted, thank you. 

I just created a major update for Slovenian language on Transifex with many improvements, so I'm looking forward for you to update it to the master :)

**Pull request merged**
