### PR TITLE
 Bugfix: Allow BoardAdmin to create board rules. Fixes #2431

### LINKED ISSUE #2431: Bug: Only FullWekanAdmin is able to create board rules
Now only WekanAdmins can create rules. Is there
a reason, why board-admins cannot create rules for their boards?

If not - can we change the line:

https://github.com/wekan/wekan/blob/d7bc8d100d1aec040e42ad9b632aa5a74fd54559/client/components/boards/boardHeader.jade#L88

to

```jade
if currentUser.isBoardAdmin 
```
?

### PR DESCRIPTION
**Pull request by road42**
Changed the check for `currentUser.isAdmin` to `currentUser.isBoardAdmin`.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/2433)

### CODE REVIEW

**Comment by road42** [comment]
@xet7 Is this PR ok or do I have to change something?

**Comment by xet7** [comment]
Both isAdmin and isBoardAdmin should be able to create rules.

**Comment by road42** [comment]
@xet7 Can "isAdmin" access every board? 

In the model only the "isBoardAdmin" is checked:

https://github.com/wekan/wekan/blob/d7bc8d100d1aec040e42ad9b632aa5a74fd54559/models/rules.js#L38-L48

**Comment by road42** [comment]
@xet7 I re-added the isAdmin.

**Pull request merged**
