### PR TITLE
Fix move selection

### PR DESCRIPTION
**Pull request by marc1006**
This fixes https://github.com/wekan/wekan/issues/3119.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3120)

### CODE REVIEW

**Comment by marc1006** [comment]
@xet7 Did I mess up the generation of the Python API once again? :/ Can fix it if it's the case.

**Comment by xet7** [comment]
@marc1006 

Yes. It's at `wekan/releases/rebuild-docs.sh` and deps at `wekan/releases/rebuild-docs-install-deps.sh`.

Well, whole day, reverting changes, trying to get Wekan working again. And it seems I get errors on CSV export again. I'll probably add info to issues about remaining issues.

**Comment by marc1006** [comment]
@xet7 Okay, I'll add a pull request for the fix. In the end we should probably fix the Python generator script.

**Comment by xet7** [comment]
@marc1006 

I will fork that python generator to wekan GitHub org, so it will be easier to fix.

**Comment by xet7** [comment]
@marc1006 

Forked repos is here:
https://github.com/wekan/esprima-python

**Pull request merged**
