### PR TITLE
Add horizontal scroll and link to open board to My Cards

### PR DESCRIPTION
**Pull request by helioguardabaxo**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3469)

### CODE REVIEW

**Comment by jrsupplee** [comment]
How does the scrolling work on mobiles?

Also what if you want the current behavior of wrapping instead of scrolling?  I personally do not like horizontal scrolling.  IMO would be better to have something you click on to enable the scrolling behavior.

**Comment by helioguardabaxo** [comment]
@jrsupplee 
I have boards with multiples lists. In My Cards this lists and its cards shows outside the boundaries.
Your suggestion is good, but I don't know how to implements.Could you help?

**Comment by jrsupplee** [comment]
I see the problem now.  There was a change made to the list style to use `table-cell` instead of `inline-block`.

```
.my-cards-list-wrapper
  margin: 1rem
  border-radius: 5px
  padding: 1.5rem
  padding-top: 0.75rem
  display: table-cell
  min-width: 250px
  max-width: 350px
```

I think it should be changed back to `inline-block`

**Comment by jrsupplee** [comment]
> @jrsupplee
> I have boards with multiples lists. In My Cards this lists and its cards shows outside the boundaries.
> Your suggestion is good, but I don't know how to implements.Could you help?

Your solution is not  a bad one for `display: table-cell` for lists.

The boards URL is a good idea, but not sure about the window to the right.  Is that symbol used elsewhere in Wekan for a link?

**Comment by helioguardabaxo** [comment]
I thought that a icon/link could create a destac, but brokes Wekan design harmony. 
It's better a text link?

Additionally, I tried to set board color, but doesn't works. I tried this: 
.my-cards-board-title(class=list.colorClass)
Any suggestion?

**Comment by jrsupplee** [comment]
> I thought that a icon/link could create a destac, but brokes Wekan design harmony.
> It's better a text link?
> 
> Additionally, I tried to set board color, but doesn't works. I tried this:
> .my-cards-board-title(class=board.colorClass)
> Any suggestion?

I think that background colors are being set in `myCards.styl`.  Inspect the webpage and see what styles are being applied.

**Comment by helioguardabaxo** [comment]
I inspected element in two differents boards in My Cards and found:
class="my-cards-board-title board-color-belize"
class="my-cards-board-title board-color-pomegranate"

If I disable background-color in myCards.styl, the element becomes transparent and keeps the class above.

**Comment by helioguardabaxo** [comment]
I found here:
.my-cards-board-title(class=board.colorClass, id="header")

It's works!

**Comment by helioguardabaxo** [comment]
I will close this PR and adjust the title link.

@jrsupplee 
Thanks for you help and suggestions

**Pull request closed without merging**
