### PR TITLE
Implement option to change the first day of the week in user settings

### PR DESCRIPTION
**Pull request by marc1006**
Implements https://github.com/wekan/wekan/issues/2535.

Screenshots:
screen
screen_2

It is a first version and hopefully it makes sense what I have done :)

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3032)

### CODE REVIEW

**Comment by marc1006** [comment]
It might also be useful to change the default value from Sunday to Monday.

**Comment by xet7** [comment]
@marc1006 

Yes, please change default value to Monday.

**Comment by marc1006** [comment]
@xet7 Okay, I will add a separate commit for changing the default.

**Comment by xet7** [comment]
@marc1006

Those are all different settings, you should not combine them.

**Comment by marc1006** [comment]
Okay, but right now, as soon as you apply a change, the "Change settings" popup will exit. I'm not sure whether this behavior is always intended.

**Comment by xet7** [comment]
@marc1006 

Yes, currently it does Popup.Close.

Wekan is going to design direction where most things are fullscreen https://github.com/wekan/wekan/issues/1574#issuecomment-609095074 . So if you like, you can combine that one popup menu, or all of those submenus to one big fullscreen settings popup, that has one Apply. If you make fullscreen popup, then you need to move also all those helpers etc also.

**Comment by xet7** [comment]
For mobile view of settings, there is isMiniScreen checks.

```
~/repos/wekan $ ./find.sh isMiniScreen
```

**Comment by xet7** [comment]
Sure starting first with only combining that one popupmenu to use one Apply is smaller first step, and a good place to start.

**Pull request merged**
