### PR TITLE
REST API  -  Meteor 1.4 - first step issue #166

### PR DESCRIPTION
**Pull request by huneau**
My first draft of a REST API. Refer here #166 .

For now, you will find resources: `user`, `board`, `list`, `card` and method: `GET`, `POST`, `DELETE`.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1003)

### CODE REVIEW

**Comment by huneau** [comment]
https://travis-ci.org/wekan/wekan/builds/221999058#L5338
why 'Oo ....

**Comment by stephenmoloney** [comment]
@huneau 
I think you have run into this issue. `https://github.com/Medium/phantomjs/issues/467`. I think this can be fixed by using a newer version of phantomjs. But it seems some other repository must be using an old of phantom js -so it might be a bit more complicated than that.

**Comment by huneau** [comment]
I have no error for me : https://gist.github.com/huneau/12dc9bdf5b3fbb4839541187b4416897

I think is just an itinerant bug. I will push a modif and it's will work

**Comment by stephenmoloney** [comment]
@huneau 
Can you merge the latest version of `wekan/meteor-1.4` and push back into this pull request with any conflicts resolved (if there are any)?
I want to try build this PR myself.

**Comment by huneau** [comment]
hey, it's compile, just a network bug ... nothing important

now I need to change my email address from commit -_-

**Comment by xet7** [comment]
I think I already manually merged this.

**Pull request closed without merging**
