### PR TITLE
PWA, move to standalone (standard) to display the status bar

### PR DESCRIPTION
**Pull request by mfilser**
in fullscreen mode this is hidden:
- at top   : status bar (current time, app notifications, battery percent)
- at bottom: navigation keys

### CODE REVIEW

**Comment by xet7** [comment]
Yes, those are intentionally hidden. It is working as designed as fullscreen.

It is not designed to show as standalone.

**Comment by xet7** [comment]
All of these apps also start in fullscreen mode and mobile, tablets, etc:

- Trello
- ClickUp
- Miro
- Planner
- Whiteboard

**Comment by mfilser** [comment]
Ok, just an idea. It interupts my work not to have the navigation at the bottom or status bar at the top, but anyways, I keep this commit for my own running instance :slightly_smiling_face:

**Comment by xet7** [comment]
If someone needs that setting to be Standalone, there should be PWA settings at Admin Panel, where to setup favicon, site.manifest options, logos, and other whitelabeling related settings.

**Comment by xet7** [comment]
Some of favicon settings can be changed in WeKan PHP prototype https://github.com/wekan/php/blob/main/settings.php but not yet in Meteor WeKan. But PHP prototype does not even have working login yet, it can not be used yet.

**Comment by mfilser** [comment]
For this idea the static page needs to be dynamically generated.
I don't have time for this feature ...

**Comment by xet7** [comment]
Hmm, there is also possibility that I'm wrong. Ok, I'll change that setting to Standalone.

**Comment by xet7** [comment]
I will add these changes to next WeKan version.

**Comment by mfilser** [comment]
I can send a PR again if you like, no problem :wink:

**Comment by xet7** [comment]
@mfilser 

That's not necessary, I already made that change at https://github.com/wekan/wekan/commit/ca5a579e225248498880f8e79d84a78b30d93cfd . Thanks anyway!

**Pull request closed without merging**
