### PR TITLE
Remove added backticks from regex

### PR DESCRIPTION
**Pull request by jrsupplee**
Inserted backticks into RegExps broke the regular expressions.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3502)

### CODE REVIEW

**Comment by xet7** [comment]
@jrsupplee 

Missing backticks did break Snap builds. When I added backticks, Snap builds started working.

**Comment by xet7** [comment]
Also, when there were missing backticks, there were error messages about quotes when building from source with Meteor.

**Comment by jrsupplee** [comment]
> Also, when there were missing backticks, there were error messages about quotes when building from source with Meteor.

It builds fine on my Linux Ubuntu box.  Problem is that search is now completely broken.  Worse it freezes the browser.

The RegExp created with `/ /` were in the code before when the builds worked.  What is new is the addition of the `u` unicode flag and the use of Unicode classes `\Letter` and `\Marker`.

**Comment by jrsupplee** [comment]
Let me try to rewrite it without using the `u` flag.

**Comment by jrsupplee** [comment]
BTW I am getting lots of errors now.  Not sure if they are related to search:

```
Exception from Tracker recompute function: meteor.js:1059:23

TypeError: eachView.initialSubviews is null meteor.js:1059:23

removedAt/<@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2688:13
module/Tracker.nonreactive@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:625:12
removedAt@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2672:17
removed@http://localhost:4000/packages/observe-sequence.js?hash=027fc9f2ee79693a7ad95bebcb456b9753cb463e:296:17
module/DiffSequence.diffQueryOrderedChanges/<@http://localhost:4000/packages/diff-sequence.js?hash=e7fa948eeff64f908873f6c77502554d52a4d615:183:68
module/DiffSequence.diffQueryOrderedChanges@http://localhost:4000/packages/diff-sequence.js?hash=e7fa948eeff64f908873f6c77502554d52a4d615:182:15
diffArray@http://localhost:4000/packages/observe-sequence.js?hash=027fc9f2ee79693a7ad95bebcb456b9753cb463e:218:9
observe/computation</<@http://localhost:4000/packages/observe-sequence.js?hash=027fc9f2ee79693a7ad95bebcb456b9753cb463e:151:18
module/Tracker.nonreactive@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:625:12
observe/computation<@http://localhost:4000/packages/observe-sequence.js?hash=027fc9f2ee79693a7ad95bebcb456b9753cb463e:125:15
_compute@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
EventListener.handleEvent*usePostMessage@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:524:12
@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:553:3
@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:558:4
@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1360:3
meteor.js:1059:23

Exception from Tracker recompute function: meteor.js:1059:23

TypeError: domrange is undefined meteor.js:1059:23

doMaterialize@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1934:11
module/Tracker.nonreactive@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:625:12
doRender@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1930:17
viewAutorun/</<@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1778:18
module/Template._withTemplateInstanceFunc@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:3575:14
viewAutorun/<@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1777:29
module/Blaze._withCurrentView@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:2109:12
viewAutorun@http://localhost:4000/packages/blaze.js?hash=a20deb597f76789e171a9ee2b2e37d73fbb7ecda:1776:18
_compute@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:331:38
_recompute@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:348:16
module/Tracker._runFlush@http://localhost:4000/packages/tracker.js?hash=5ef67b97eaf2ca907dc38459283f2349bada6814:515:14
onGlobalMessage@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:515:23
EventListener.handleEvent*usePostMessage@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:524:12
@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:553:3
@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:558:4
@http://localhost:4000/packages/meteor.js?hash=857dafb4b9dff17e29ed8498a22ea5b1a3d6b41d:1360:3
meteor.js:1059:23
```

**Comment by jrsupplee** [comment]
The above error seems to have been a data problem.

**Comment by xet7** [comment]
@jrsupplee 

Those errors could be related to any recent change.

**Comment by jrsupplee** [comment]
I reloaded my data and they went away

**Comment by jrsupplee** [comment]
I replaced all the regexs defined with slashes to use `new RegExp(...)`.  Let's see if snap will build with these.

**Pull request closed without merging**
