### PR TITLE
Fix Trello importation for ChecklistItems

### PR DESCRIPTION
**Pull request by zebby76**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1611)

### CODE REVIEW

**Comment by xet7** [comment]
@zebby76 

Do you have possibility to add another pull request that fixes npm lint errors? See developer docs at Wekan GitHub wiki.

**Comment by xet7** [comment]
@zebby76 

Nevermind, I got those lint errors fixed.

**Comment by szeberli** [comment]
Import from Wekan-Export not woking :(

**Comment by xet7** [comment]
@szeberli 

This is about Import from Trello, not import from Wekan-Export. Please add new issue.

**Comment by zebby76** [comment]
@szeberli 

See this [fix](https://github.com/wekan/wekan/pull/1613) for Wekan-Export issue.

**Pull request merged**
