### PR TITLE
REST API features

### PR DESCRIPTION
**Pull request by mayjs**
This pull requests extends the REST API and changes the authorization system for some of the endpoints.
It implements some of the features listed in #1037. All changed or added endpoints are read-only.

The following changes were made:

- Add additional functions to `authentication.js`. It is now possible to check if a user should get access to a given board.
- Added the endpoint `GET /api/user` which allows to get basic information about the API user.
- Added the endpoint `GET /api/user/boards`. This endpoint can be used to get all boards this user is part of.
- Changed the reading access methods created by @huneau to be usable by any logged in user. I used a new authorization function which grants access to every board for admins, but restricts access for normal users. This change currently only affects boards, lists and cards, which are my main concern to be able to access.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1041)

### CODE REVIEW

**Comment by huneau** [comment]
Hi @mayjs,

I not sure about that `GET /api/user/boards` this is not RESTFUL.
You use the request.userId to get the user but in REST you should use `GET/api/users/:userId/boards`
Otherwise it's good for me.

**Comment by mayjs** [comment]
@huneau thanks for your feedback. You are right, it would be better to use `GET /api/users/:userId/boards`. I will fix this issue and add it to this PR.

**Comment by huneau** [comment]
you have missed a `s` to `/user`

**Comment by mayjs** [comment]
Oh yeah you are right. It's fixed.

**Pull request merged**
