### PR TITLE
pradeepgokul's-patch

### PR DESCRIPTION
**Pull request by pradeepgokul**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1079)

### CODE REVIEW

**Comment by xet7** [comment]
@pradeepgokul 

Please [remove commits from pull requests](https://stackoverflow.com/questions/36168839/how-to-remove-commits-from-pull-request) that touch other files than those that are necessary for your new feature.

When you add new commits, please add some descriptive text that's different from "updates for new commits".

This way there would be less possibility of merge conflicts.

Thanks!

**Comment by xet7** [comment]
Please edit your pull request name what feature this adds, and also edit comment of pull request to add summary what parts it contains. Thanks!

**Comment by jLouzado** [comment]
@pradeepgokul why did you go into the `flexiple` fork of the project and pull code? That code was for some features that aren't really applicable here. :sweat:

**Comment by jLouzado** [comment]
@xet7 I don't think this really has any customFields code from the looks of it... But I could try and cherry pick the new commits and see what kind of changes have been introduced, if that helps.

**Comment by pradeepgokul** [comment]
@jLouzado I'm aware of that, I'll be removing the commits as soon as possible

**Comment by jLouzado** [comment]
@pradeepgokul just create a new branch and cherry pick only your commits to it. Then that'll be only your features.

Also please try and keep your commit messages meaningful and related to the changes made. `Some commits`, `some more commits` etc are difficult to parse.

**Pull request closed without merging**
