### PR TITLE
Admin reports & Show Card Creator

### PR DESCRIPTION
**Pull request by jrsupplee**
Pull request adds:
* Admin reports.  An option added to the admin panel that has reports an admin can run.  Right now it has two reports for attachments and broken cards.
* Add the creator avatar to `cardDetails` and `minicard`.  Avatar is only shown if it is selected in card settings.
* Added a new search operator `creator`
* Bug fix for multiple label predicates.

Sorry stuffing so much in a single pull request.

Refs: #3681

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/3705)

### CODE REVIEW

**Comment by twnk** [comment]
https://github.com/wekan/wekan/pull/3705/commits/302ba75729102e6fbb848ebefe898a5a7403fb05 introduced a bug. specifically https://github.com/wekan/wekan/blame/424862e31353e3099208ffc2d2cc34f0674e2060/models/cards.js#L284-L291 introduced a card type requirement without any kind of schema migration to update cards with invalid card types. Had to migrate manually.

```json
{'_id': 'hbsQ9Kg4MwXPLJcuh',
 'archived': False,
 'assignedBy': 'Whoever',
 'assignees': [],
 'boardId': 'gw3vZRBqYMsrFZHwR',
 'coverId': '',
 'createdAt': datetime.datetime(2021, 2, 27, 21, 55, 56, 241000),
 'customFields': [{'_id': 'rngkF4wcxjFFRBABk', 'value': None},
                  {'_id': 'TBfFLP7ocmGm2etH9', 'value': None},
                  {'_id': 'b5qKBBSgLjipaAiLo', 'value': None},
                  {'_id': 'rn3QQehDmWoZzKkFr', 'value': None}],
 'dateLastActivity': datetime.datetime(2021, 2, 27, 21, 55, 56, 241000),
 'description': '',
 'isOvertime': False,
 'labelIds': ['pBB2Hw'],
 'linkedId': '',
 'listId': 'p7cqX9DhRb9QZqKnm',
 'members': [],
 'modifiedAt': datetime.datetime(2021, 2, 27, 21, 55, 56, 241000),
 'parentId': '',
 'receivedAt': None,
 'requestedBy': 'Contact Form',
 'sort': 13,
 'spentTime': 0,
 'subtaskSort': -1,
 'swimlaneId': 'yGg5esWfaoW2xAd9k',
 'title': 'Template',
 'type': 'template-card',
 'userId': '5AJjkzw7BRamB2H4X',
 'vote': {'allowNonBoardMembers': False,
          'end': None,
          'negative': [],
          'positive': [],
          'public': False,
          'question': ''}}
```
card with this representation in mongodb would error when attempting to copy it. export and reimport, or the following db command, fixed it 
```python
wk._db.cards.update(
        {'_id':'hbsQ9Kg4MwXPLJcuh'},
        {'$set': {
            'type': 'cardType-card'
        }}
    )
```
after this it has a legal type and can be copied
```json
{'_id': 'hbsQ9Kg4MwXPLJcuh',
 'archived': False,
 'assignedBy': 'Whoever',
 'assignees': [],
 'boardId': 'gw3vZRBqYMsrFZHwR',
 'coverId': '',
 'createdAt': datetime.datetime(2021, 2, 27, 21, 55, 56, 241000),
 'customFields': [{'_id': 'rngkF4wcxjFFRBABk', 'value': None},
                  {'_id': 'TBfFLP7ocmGm2etH9', 'value': None},
                  {'_id': 'b5qKBBSgLjipaAiLo', 'value': None},
                  {'_id': 'rn3QQehDmWoZzKkFr', 'value': None}],
 'dateLastActivity': datetime.datetime(2021, 2, 27, 21, 55, 56, 241000),
 'description': '',
 'isOvertime': False,
 'labelIds': ['pBB2Hw'],
 'linkedId': '',
 'listId': 'p7cqX9DhRb9QZqKnm',
 'members': [],
 'modifiedAt': datetime.datetime(2021, 2, 27, 21, 55, 56, 241000),
 'parentId': '',
 'receivedAt': None,
 'requestedBy': 'Contact Form',
 'sort': 13,
 'spentTime': 0,
 'subtaskSort': -1,
 'swimlaneId': 'yGg5esWfaoW2xAd9k',
 'title': 'Template',
 'type': 'cardType-card',
 'userId': '5AJjkzw7BRamB2H4X',
 'vote': {'allowNonBoardMembers': False,
          'end': None,
          'negative': [],
          'positive': [],
          'public': False,
          'question': ''}}
```

**Comment by xet7** [comment]
Not every card is `cardType-card`. Some cards are linked card. Maybe this needs some migrations at `wekan/server/migrations.js` ? @jrsupplee can you try to fix this?

**Comment by xet7** [comment]
Hmm nevermind, maybe https://github.com/wekan/wekan/pull/3723 fixes this.

**Comment by jrsupplee** [comment]
What I added was the `allowedValues` which I meant to have a discussion about before adding it.  Sorry about that.

```
   type: {
      /**
       * type of the card
       */
      type: String,
      defaultValue: TYPE_CARD,
      allowedValues: [TYPE_CARD, TYPE_LINKED_CARD, TYPE_LINKED_BOARD],
    },
```

If it needs to be removed, that is possible or the better option would be a migration.

**Comment by jrsupplee** [comment]
@twnk 

> 302ba75 introduced a bug. specifically https://github.com/wekan/wekan/blame/424862e31353e3099208ffc2d2cc34f0674e2060/models/cards.js#L284-L291 introduced a card type requirement without any kind of schema migration to update cards with invalid card types. Had to migrate manually.

What were the values in the fields?

**Comment by jrsupplee** [comment]
@xet7 

> Not every card is `cardType-card`. Some cards are linked cards. Maybe this needs some migrations at `wekan/server/migrations.js` ? @jrsupplee can you try to fix this?

The allowed types for cards, that I could find in the system are `card`, `linked`, and `linked-board`.  Are there others?

**Comment by jrsupplee** [comment]
@xet7 

How is this for a migration?

```
Migrations.add('cards-fix-illegal-type', () => {
  Cards.update(
    {
      type: {
        $nin: [TYPE_CARD, TYPE_LINKED_CARD, TYPE_LINKED_BOARD],
      },
    },
    {
      $set: {
        type: TYPE_CARD,
      },
    },
    noValidateMulti,
  );
});
```

Given:

```
export const TYPE_CARD = 'cardType-card';
export const TYPE_LINKED_BOARD = 'cardType-linkedBoard';
export const TYPE_LINKED_CARD = 'cardType-linkedCard';
```

**Comment by xet7** [comment]
Well, there is `template-card`, `template-list`, `template-swimlane`, `template-container` etc but I don't know which ones this should affect, anyway this kind of changes seem dangerous so they need some testing.

**Comment by jrsupplee** [comment]
Easiest solution for now is to remove `allowedValues` from the schema for `Cards.type`

**Comment by twnk** [comment]
> @twnk
> 
> > [302ba75](https://github.com/wekan/wekan/commit/302ba75729102e6fbb848ebefe898a5a7403fb05) introduced a bug. specifically https://github.com/wekan/wekan/blame/424862e31353e3099208ffc2d2cc34f0674e2060/models/cards.js#L284-L291 introduced a card type requirement without any kind of schema migration to update cards with invalid card types. Had to migrate manually.
> 
> What were the values in the `type` field for broken cards?

I only discovered ones with type 'template-card'. If it's useful, I could run a query to see if there are any others?

**Pull request merged**
