### PR TITLE
Add card spent time to log time what can be overtime or not (will support filtering in future)

### PR DESCRIPTION
**Pull request by thuanpq**
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1340)

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
The notion that xet7 commits fail the CLA is hilarious, as a sidenote. Is it possible to submit the PR without the extra commits though?

**Comment by xet7** [comment]
I have now signed the CLA.

**Comment by xet7** [comment]
@thuanpq 

Please get latest wekan/wekan devel branch, add all your changes of this pull reques, close this pull request, and make new pull request to devel branch with only your changes. So that there is no my commits.

**Comment by xet7** [comment]
@thuanpq 

This still contains my old unreleased git tag v0.53 etc. Please don't merge latest changes, but make a new pull request instead.

**Pull request closed without merging**
