### PR TITLE
Adding Folders (Boards contenitors)

### PR DESCRIPTION
**Pull request by john9838**
Hello, I think Wekan is fantastic. I'm wondering if it would be possible to add the ability to create folders. So we can use them as boards containers. Basically, in the first window, we would see: ADD FOLDER / ADD BOARD instead of only "ADD BOARD"

For example Folder X contains 7 boards. Folder Y contains 11 boards. 
 
I believe if you made Wekan, which is so powerful, this feature should be possible.

Thanks to everyone contributing to the Wekan Project. 
Thanks to xet7 !

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/4123)

### CODE REVIEW

**Comment by xet7** [comment]
I tried to manually look merging this, but layout looks to be messed up.

**Comment by john9838** [comment]
No prob really. I thought it was easier to make it. Thank you so much for giving it a try so quickly. Thanks.

**Comment by john9838** [comment]
@xet7 My question may sound weird to you. :) I did apply the files changed in this thread and I see no change at all in my Wekan. Once edited the files I've also restarted snap. Should I do anything else other than 1. git clone Wekan, 2. edit those files, 3 restart snap service?

**Comment by xet7** [comment]
@john9838 

Developing [with source](https://github.com/wekan/wekan/wiki/Emoji) does not affect snap in any way, until I have accepted pull request and released a new Snap version.

**Comment by john9838** [comment]
@xet7 following that source, when building Wekan I have this error showing up: /wekan# meteor npm install markdown-it-something --save
Command 'meteor' not found

Any thoughts? Searching I found it can be a path issue. Thanks.

**Comment by xet7** [comment]
You need to add to your `.bashrc` so you find meteor command:
```
PATH=%PATH:~/.meteor
```

**Comment by john9838** [comment]
my .bashrc
export PATH=/snap/wekan/1798/programs/server/npm/node_modules/meteor:$PATH

and it does not work.  I tried adding /meteor/meteor but it does not work either

**Comment by xet7** [comment]
That command:
```
npm -g install meteor
```
Should install meteor to any of:
```
/home/username/.meteor

/root/.meteor
```

**Comment by john9838** [comment]
@xet7 if I grep meteor is here
/home/.meteor/meteor

Here is my bashrc:
export PATH=/home/.meteor/meteor:$PATH

After Build Wekan:
Building Wekan.
./rebuild-wekan.sh: line 84: meteor: command not found
./rebuild-wekan.sh: line 85: meteor: command not found
./rebuild-wekan.sh: line 87: pushd: .build/bundle/programs/server: No such file or directory
./rebuild-wekan.sh: line 90: meteor: command not found
./rebuild-wekan.sh: line 92: popd: directory stack empty
Done.

I'm sure it goes beyond your support. Anyways I'm stuck here.

**Comment by xet7** [comment]
@john9838 

You see your home directory with:
```
ls /home
```
For example, if your username is john:
```
export PATH=/home/john/.meteor:$PATH
```
This is because these are directories:
```
/home

/home/john

/home/john/.meteor
```
And this is script plain text file that has commands (not directory). PATH environment variable lists directories where it tries to find commands:
```
/home/john/.meteor/meteor
```
Then close terminal, and open it again, and try that:
```
cd repos/wekan

./rebuild-wekan.sh
```

**Comment by xet7** [comment]
Sorry this PR is broken. Please make new working PR.

**Comment by john9838** [comment]
no prob. My home directory is home/.meteor/meteor
Apparently there isn't any user between home and .meteor
Anyway thank you so much for all your help.
I will start using Wekan as it is. That is great.
Hopefully I may contribute too soon. Thank you again.

**Pull request closed without merging**
