### PR TITLE
Separate system & app layers in Dockerfile

### PR DESCRIPTION
**Pull request by eemeli**
As is, the Dockerfile produces a single layer that needs to be re-generated for any change in Wekan, i.e. from the OS layer upwards. That's a bit wasteful, so I've here separated the system and application layers from each other, which allows the build process to speed up at least a bit.

It's still rather cumbersome for development, but that'll require slightly deeper changes.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/874)

### CODE REVIEW

**Comment by xet7** [comment]
@eemeli 

I got some errors when doing local Docker build with this:

```
> fibers@1.0.15 install /usr/lib/node_modules/fibers
> node build.js || nodejs build.js

gyp WARN EACCES user "undefined" does not have permission to access the dev dir
 "/root/.node-gyp/0.10.48"
gyp WARN EACCES attempting to reinstall using temporary dev dir
 "/usr/lib/node_modules/fibers/.node-gyp"
make: Entering directory `/usr/lib/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
  CXX(target) Release/obj.target/fibers/src/coroutine.o
  CC(target) Release/obj.target/fibers/src/libcoro/coro.o
  SOLINK_MODULE(target) Release/obj.target/fibers.node
  COPY Release/fibers.node
make: Leaving directory `/usr/lib/node_modules/fibers/build'
Installed in `/usr/lib/node_modules/fibers/bin/linux-x64-11/fibers.node`
/usr/lib
`-- fibers@1.0.15 

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7786    0  7786    0     0  13726      0 --:--:-- --:--:-- --:--:-- 20986
Starting meteor 1.3.5.1 installation...   

Downloading Meteor distribution

Meteor 1.3.5.1 has been installed in your home directory (~/.meteor).

Now you need to do one of the following:

  (1) Add "$HOME/.meteor" to your path, or
  (2) Run this command as root:
        cp "/home/wekan/.meteor/packages/meteor-tool/1.3.5_1/mt-os.linux.x86_64/scripts/admin/launch-meteor" /usr/bin/meteor

Then to get started, take a look at 'meteor --help' or see the docs at
docs.meteor.com.
 ---> 8aa0855c888d
Removing intermediate container c3b59c2b68e5
Step 16/20 : COPY ${SRC_PATH} /home/wekan/app
 ---> 148d32c923ea
Removing intermediate container 2860bff58512
Step 17/20 : RUN chown wekan:wekan --recursive /home/wekan/app &&
     cd /home/wekan/app &&
     gosu wekan /home/wekan/.meteor/meteor npm install --save xss &&
     gosu wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build &&
     cd /home/wekan/app_build/bundle/programs/server/ &&     gosu wekan npm install &&
     mv /home/wekan/app_build/bundle /build &&
         apt-get remove --purge -y ${BUILD_DEPS} &&
     apt-get autoremove -y &&
     rm -R /var/lib/apt/lists/* &&
     rm -R /home/wekan/.meteor &&
     rm -R /home/wekan/app &&
     rm -R /home/wekan/app_build &&
     rm /home/wekan/install_meteor.sh
 ---> Running in ea02a0b5855c
npm ERR! Linux 4.4.0-64-generic
npm ERR! argv "node" "/home/wekan/.meteor/packages/meteor-tool/1.3.5_1/mt-os.linux.x86_64/dev_bundle/bin/npm" "install" "--save" "xss"
npm ERR! node v0.10.46
npm ERR! npm  v3.10.5
npm ERR! path /home/wekan/app/node_modules/xss
npm ERR! code EXDEV
npm ERR! errno 52

npm ERR! EXDEV, rename '/home/wekan/app/node_modules/xss'
npm ERR! 
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/wekan/app/npm-debug.log
The command '/bin/sh -c chown wekan:wekan --recursive /home/wekan/app &&
     cd /home/wekan/app &&
     gosu wekan /home/wekan/.meteor/meteor npm install --save xss &&
     gosu wekan /home/wekan/.meteor/meteor build --directory /home/wekan/app_build &&
     cd /home/wekan/app_build/bundle/programs/server/ &&
     gosu wekan npm install &&
     mv /home/wekan/app_build/bundle /build &&
         apt-get remove --purge -y ${BUILD_DEPS} &&
     apt-get autoremove -y &&
     rm -R /var/lib/apt/lists/* &&
     rm -R /home/wekan/.meteor &&
     rm -R /home/wekan/app &&
     rm -R /home/wekan/app_build &&
     rm /home/wekan/install_meteor.sh' returned a non-zero code: 52
```

And when looking at sizes of built local Docker images:
```
$ docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
<none>              <none>              148d32c923ea        6 minutes ago       1.1 GB
debian              wheezy              c0b3d08fde7a        27 minutes ago      85.3 MB

```
And sizes at Docker Hub:
```
Tag Name  Compressed Size  Last Updated
latest           88 MB                  2 days ago
```
Does this increase size of compressed Docker image on Docker Hub?

**Comment by eemeli** [comment]
@xet7 You're right, the intermediate layer does add an unnecessary 900MB or so to the image size. So this isn't really a viable approach.

Still, I'd like to use/enable a dockerised environment for development. In practice, this would mean needing separate Dockerfiles for development and production; possibly separate docker-compose configs as well. I've got a working set of changes for that locally, but before I replace this branch with them, a few questions:
- Should the default be for development or production?
- Should scripts be added to `package.json` for these builds, and/or should we add a `Makefile` for them? Not doing either is also a valid option.
- Should the use case of using Docker but not using docker-compose be supported?

The `EXDEV` error looks like a weird thing possibly caused by aufs. I'm not seeing it in my own environment, and it may go away thanks to the further changes I'm making to the docker config.

**Comment by xet7** [comment]
@eemeli

We have various Wekan related Docker Compose, installation, logfile etc repos under
https://github.com/wekan
GitHub Organization, and each repo has main developer that maintains those mostly independently.

If there is not already existing repos for various purposes you mentioned already, I can create new repos for you.

**Comment by xet7** [comment]
@eemeli 

Because of size increase I will not merge this pull request and will close pull request.

Please add new issue or pull request for different Wekan repo, or about creating new Wekan repo.

**Pull request closed without merging**
