### PR TITLE
Fix language bug

### PR DESCRIPTION
**Pull request by liuliming2008**
I have tested on zh-CN

### CODE REVIEW

**Comment by mquandalle** [comment]
Looks good! Before I merge this could you fix the weird space on line 18 (and `git commit --amend`, `git push -f`), and sign the CLA?

**Comment by mquandalle** [comment]
Related to #310.

**Comment by mquandalle** [comment]
Why did you close this?

**Comment by liuliming2008** [comment]
I modified this file directly on wekan github at browser to commit the pull, and lead the wired space.
And now I dont not how to commit one single file of my fork to wekan.
Maybe I have to checkout wekan to local and commit the modified file.

**Pull request closed without merging**
