### PR TITLE
Admin panel:

### PR DESCRIPTION
**Pull request by lkisme**
Only invited user can register in strict mode,
Set mail server in admin panel,
Switch strict mode in admin panel,
Invite people to system in admin panel.

Resolve the conflicts, ready for review, code is identical with #618 .

PS: The UE inside of Admin Panel(such as sending invitation) is not very nice, since I'm not a very front-end guy, maybe someone else can help on that.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/871)

### CODE REVIEW

**Comment by ocdtrekkie** [comment]
As a note for @xet7, if the settings here are limited to the ones listed above, the admin panel should probably just not be displayed for Sandstorm users, as none of these settings would apply to them.

**Comment by xet7** [comment]
Please remove i18n/zh-CN.i18n.json from pull request. Translations from English to other languages are done at Transifex: https://www.transifex.com/wekan/wekan

---

Review status: 0 of 20 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/wekan/wekan/871#-:-KdkcgiWw9ECFgVcK5_D:bdlk4ow)*

**Comment by lkisme** [comment]
@xet7 Done.

**Comment by xet7** [comment]
@lkisme 

When I tried to run Wekan with your pull request with my existing cards etc in MongoDB, I got this error:

```
$ ./run-wekan.sh 

/home/user/repos/wekan/.build/bundle/programs/server/node_modules/fibers/future.js:280
						throw(ex);
						      ^
Error: Username is required
    at getErrorObject (packages/aldeed_collection2-core/lib/collection2.js:437:1)
    at [object Object].doValidate (packages/aldeed_collection2-core/lib/collection2.js:420:1)
    at [object Object].Mongo.Collection.(anonymous function) [as insert] (packages/aldeed_collection2-core/lib/collection2.js:173:1)
    at models/settings.js:57:16
    at /home/user/repos/wekan/.build/bundle/programs/server/boot.js:304:5
```

**Comment by lkisme** [comment]
@xet7 The error should be gone.

BTW, you need name an admin among existing users if you already ran the project before by execute bellowing expression in the console of mongo:

> db.users.update({username:'xxx-ur-user-name'},{$set:{isAdmin:true}})

**Comment by xet7** [comment]
@lkisme 

In Admin Panel, please rename:
Settings / System / Use Strict Mode
to
Settings / Registration / Disable Self-Registration

**Comment by xet7** [comment]
@lkisme 

1) Please rename everywhere in code, MongoDB database etc:
Admin Panel / Settings / System / Use Strict Mode
to
Admin Panel / Settings / Registration / Disable Self-Registration
and also please tell me how do I make those renames to my existing MongoDB database.

2) Please add text from Admin Panel to English translations, if there is some text missing.

3) Please make Admin panel at for example url http://localhost:3000/setting require login, because on webbrowser new window incognito mode it is visible without user data.

@dwrensha 

Do you have recommendations for hiding Admin Panel? In what cases is isMiniScreen used etc? Would hiding just Admin Panel menu option be enough? On elsewhere in code there is Javascript code like:

```
if (!isSandstorm) {
...
}
```
And in templates:
```
unless isMiniScreen
  unless isSandstorm
```

**Comment by lkisme** [comment]
@xet7 Just run `db.settings.remote({})`.

**Comment by ocdtrekkie** [comment]
@xet7 Do you know how this appears (hopefully doesn't) in Sandstorm yet? This will be the one thing we need to test for rc2 in Sandstorm, I think.

**Comment by xet7** [comment]
@ocdtrekkie 

Discussion moved to https://github.com/wekan/wekan/issues/790

**Pull request merged**
