### PR TITLE
List header contains now a button to add the card to the bottom of the list

### PR DESCRIPTION
**Pull request by mfilser**
adding a button to add cards at the bottom of the list.
Here is a screenshot (see green marker)
grafik

I haven't found a better icon on https://fontawesome.com/icons

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/4195)

### CODE REVIEW

**Comment by xet7** [comment]
@mfilser 

AFAIK WeKan uses https://fontawesome.com/v4.7/icons/

**Comment by xet7** [comment]
@mfilser 

You could try combination of `+` and some up or down icons, if you would like to have something like that.

**Comment by mfilser** [comment]
Good idea to use a combination of 2 icons. I am not sure if the "user" see the 2 icon as one icon or expect to have 2 "features".

**Comment by xet7** [comment]
User does see it as one icon, if you add some shadow or border to below of those 2 combined icons.

**Comment by mfilser** [comment]
I will try it, thank you :slightly_smiling_face:

**Comment by mfilser** [comment]
@xet7 
I added a arrow down icon, it looks now: (only green highlighted for the screenshot)
grafik

If you like, it's "merge able" :slightly_smiling_face:

**Comment by helioguardabaxo** [comment]
@mfilser 
If "create card on top" has an arrow (top arrow), the list header will be polluted?

**Comment by mfilser** [comment]
@helioguardabaxo
I don't understand it correctly. Can you maybe send a screenshot or something else which explains it in another way?

**Comment by helioguardabaxo** [comment]
@mfilser 
Something like this:
143678495-ac591b1e-830f-4878-945b-02526b94fb17

**Comment by mfilser** [comment]
I see, thank you a lot for your screenshot. That's a good idea, i will check it and try if there is enough space at mobile view too

**Comment by mfilser** [comment]
grafik

**Comment by mfilser** [comment]
"Merge able" again if it's "good enough" :slightly_smiling_face:

**Comment by xet7** [comment]
Unfortunately, those buttons take away some of that precious space of list name. Also when list title is long, both those new buttons of `creating new card to top/bottom` and current one `button of creating new card to top` are top or below of list title, making hard to see both list title text and that button.

Well, maybe:

a) It should be fixed that buttons are not below or top of list title

b) That `Add card top top` and `Add card to bottom` should be at list hamburger menu at top of menu

But I don't know yet what would make most sense, I should think sometime. Or, if someone creates PR that makes more sense.

**Comment by mfilser** [comment]
Well, that's right, i didn't think of long list names.
I think i move "add card to bottom" to the hamburger menu and send the new commits here.

**Comment by mfilser** [comment]
@xet7 
Moved to hamburger menu

**Comment by mfilser** [comment]
Thank you for the screenshot.
This overlap is here since month/years, it wasn't introduced by this PR. This PR only changes the Hamburger Menu.

**Comment by xet7** [comment]
@mfilser 

Oh OK ! Thanks! I will merge this later so this will be in WeKan v5.82 . Currently I'm releasing WeKan v5.81 .

**Comment by mfilser** [comment]
@xet7 
Great, thank you.
I add it to my "todo" list and send a seperate PR if i find a solution.

**Pull request merged**
