### PR TITLE
fix ie dispay bug, add features: collaborate permission/team/vote/search

### PR DESCRIPTION
**Pull request by liuliming2008**
fix ie dispay bug
fix language bug
add board permision type:collaborate.Registed user can add and edit content, will automatically become member after actions
add feature: team 
add reature: vote for card
add feature: search filter
add feature: sort cards

[Review on Reviewable](https://reviewable.io/reviews/wekan/wekan/310)

### CODE REVIEW

**Comment by liuliming2008** [comment]
migration not finished

**Comment by mquandalle** [comment]
Hey @liuliming2008, thank you for this big pull request! You changed a lot of unrelated things (2 fixes and 5 new features if I understand it correctly). Could you put these is separate commits and rebase on top of master (currently there is some conflicts with master)?

**Comment by liuliming2008** [comment]
hi @mquandalle：
1 I have tried to make a pull with wekan/master, it can be merged and have no conflict. My version is based on newest wekan/master. This pull is made to devel. I can make another pull to master?
2 I do these work together, and can not divide these to separate commits.

**Comment by mquandalle** [comment]
Yes, sorry I meant `devel`, new features are implemented in `devel` first. Also this PR currently don't match my standards to be merged as in because:

* There is commented code in at least 3 different places
* 5 different features and 2 bug fixes implemented (I need to review one by one)
* Doesn't pass `eslint ./`
* Misses some comments about the modified code

So unless you can improve the quality of this submission, it will take a lot of re-work for me to get it merged.

**Comment by mquandalle** [comment]
For instance could you extract the code that is related to `fix ie dispay bug` and open a PR with it?

**Comment by liuliming2008** [comment]
I can fix the issues like:
    *There is commented code in at least 3 different places
    * Doesn't pass eslint ./
    *Misses some comments about the modified code

But really diffifuclt to divide these to separate commits.  Modified many files in many days.

**Comment by mquandalle** [comment]
I've pulled your PR locally and tested it, and I definitely can’t merge it as in because it changes too much things (including the UI) and introduces some bugs and non-consistent schemes. You also implement some features that weren’t discussed before and I’m not sure we want them — such as the card sorting option. I strongly recommend taking a step-by-step approach here in order to get anything merged, and I will help.

At least could you try to isolate the lines related to the bugs fixing and `cherry-pick` them in a separate PR based on `devel`?

**Comment by liuliming2008** [comment]
HI @mquandalle:
1 language fix makes a pull
2 ie display have no fug on lastest wekan devel, no need to pull
3 I re-roganized the ui to make it more like trello, and flexible enough to let me add organization pages easily.
I will merge latest wenkan/devel to my version, and fulfil schemes migrations and eslint , and sumit a pull for anyone test. But need  more time to submit seperate feature.

**Comment by liuliming2008** [comment]
hi @mquandalle，
I integrate the latest wekan some days ago, and deployed to smoch.cn, you can have a try.
But I havent finished eslint and migration.

**Comment by mquandalle** [comment]
I’m really sorry but I have to close this pull request. A pull request literally mean that you ask me, the project maintainer, to pull your branch into the main one. Unfortunately as I explained above this branch changes too many things to have a chance to get merged (along with the dirty commit history, changes in the UI, etc.)

We will have a plugin system soon enough, I hope we will be able to re-implement most of these feature on top of it.

**Comment by liuliming2008** [comment]
looking for that
thanks

**Pull request closed without merging**
