### PR TITLE
Added hide/show to show counters and members on All Boards (Admin Panel)

### PR DESCRIPTION
**Pull request by helioguardabaxo**
This PR implements feature suggested on: 
https://github.com/wekan/wekan/pull/4477#issuecomment-1213428784

### CODE REVIEW

**Comment by xet7** [comment]
@helioguardabaxo 

You seem to like this advanced Meteor WeKan version a lot and add features and fixes in PRs like some FOSS superhero. Nice going there man!

**Comment by xet7** [comment]
@helioguardabaxo

I would presume you are one of those that use most Meteor WeKan features daily and like to just add some more features.

**Comment by xet7** [comment]
@helioguardabaxo 

I mean, mostly what I get, is complaints about how slow current Meteor WeKan is with all those huge amount of amazing features. But you just go full steem ahead, thinging that there are not enough features yet, and add just another kitchen sink to the kitchen sink, to make Meteor WeKan even more amazing. It seems you are some super programmer.

**Comment by helioguardabaxo** [comment]
@xet7 
Thanks for your words of encouragement! I just am public servant that want to be a programmer.
I really like to contribute with Wekan and believe it is very useful for agile teams. 
I would like to create Kanban Metrics in Wekan. It's my "Must Have" for the future to work with some teams and focus on flow.

**Comment by helioguardabaxo** [comment]
@xet7 
I saw that you trying to create a lightweight Wekan version. Did you consider Kanboard as alternative?

**Comment by helioguardabaxo** [comment]
@xet7 
For Wekan Meteor, transform some features in plugins would not a alternative to reduce JS bundle? If admin prefers, he could active a specific feature for some boards.

**Comment by xet7** [comment]
@helioguardabaxo 

> I saw that you trying to create a lightweight Wekan version. Did you consider Kanboard as alternative?

I don't know yet does PHP run on serverless etc other platforms. Javascript is available on most platforms.

> For Wekan Meteor, transform some features in plugins would not a alternative to reduce JS bundle? If admin prefers, he could active a specific feature for some boards.

Moving feature to plugin does not make a difference. Moving code from frontend to backend does make a difference.

**Pull request merged**
