### PR TITLE
Added members list and board card count per list on My Boards

### PR DESCRIPTION
**Pull request by helioguardabaxo**
Hi @xet7 

This PR implements on My Boards:
- Card count per list
- Members list

For each board it's possible enable/disable show these info on My Boards
On sidebar:
-> "Board Settings" -> "Board info on My Boards" 

I did not find a way to change popup header:
Screenshot 2022-04-15 at 12-47-00 Board 5 -

Do you know how to fix it?
Thanks!

### CODE REVIEW

**Comment by mfilser** [comment]
@helioguardabaxo
Is there a chance to make your feature available for mobile view too? Or what's the reason to exclude the mobile view? 

https://github.com/helioguardabaxo/wekan/blob/ab077e7eb9612707a0fd6bab60e966ced36e3d43/client/components/boards/boardsList.jade#L97

Thank you for your contribution 🙂

**Comment by xet7** [comment]
@mfilser 

I added to mobile view too.

**Comment by helioguardabaxo** [comment]
@mfilser 
I don't have fluency with Flexbox and boards appear strangely  with a lot of lists. That's why I "removed" mobile view. :(

**Comment by helioguardabaxo** [comment]
This PR implements #4415

**Comment by ViViDboarder** [comment]
This is neat, but is there a setting to disable this for all boards? Or do I have to toggle it for each?

**Comment by aov-arnold** [comment]
> This is neat, but is there a setting to disable this for all boards? Or do I have to toggle it for each?
@helioguardabaxo Is there an way to disable the card counter for all boards or change the default to disabled?

**Comment by xet7** [comment]
@helioguardabaxo @ViViDboarder @aov-arnold 

> Is there an way to disable the card counter for all boards or change the default to disabled?

There is no such feature yet. If someone likes to have it, that someone can send PR to add new button for it to Admin Panel.

1) Look at what board field it is: https://github.com/wekan/wekan/pull/4477/files

2) And then add button to change all boards with button, like this: https://github.com/wekan/wekan/commit/a249ffc8054189d8e3db9b4c8f082cc7ce7dcb52

3) Send PR like this: https://github.com/wekan/wekan/wiki/Emoji

**Comment by aov-arnold** [comment]
@helioguardabaxo Would it be an option to disable the counters per default? Then you could enable it  for specific boards.

**Comment by helioguardabaxo** [comment]
@aov-arnold
I will try to figure out how to implement this option

**Comment by aov-arnold** [comment]
Thank you very much!

**Pull request merged**
