### PR TITLE
Fix: Add Feature: REST API: Create user despite disabling registration https://github.com/wekan/wekan/issues/1249

### PR DESCRIPTION
**Pull request by soohwa**
I just did set optional to false instead of true ...
Sorry ... :-D

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1251)

### CODE REVIEW

**Comment by xet7** [comment]
@soohwa 

With this new pull request:
- Wekan install with creating first user admin etc works
- When I use REST API, it looks like it did create new user
- But I can not login as new user with new user's username and password

Thanks, there's progress! :)

**Comment by soohwa** [comment]
I will take a look

**Comment by xet7** [comment]
@soohwa 

Now when I create new user with API, and login as new user, new user has admin rights. I tried to setup fromAdmin: false, but I did not yet find a way to create non-admin user. Is there a way, or can you add it?

**Comment by soohwa** [comment]
I will take a look

**Comment by soohwa** [comment]
I assume you have already a first user who is the admin (it is the desired behaviour). I cannot reproduce the creation of a second user who will have admin rights :-(

**Comment by xet7** [comment]
Yes.

1) I did create at Wekan webpage first user that became admin.

2) Then I created new user with rest api.

3) But new user has admin rights.

4) How can I create normal user with rest api? User that doea not have admin rights?

4) How to create normal user wirh

**Comment by soohwa** [comment]
The point 3 is really weird because there is nothing in the code which grant the new user as admin (isAdmin = true). And when I log in in the interface with the second user I'm not admin and when I retrieve the user's information via /api/users/:id there is no presence of isAdmin. So I really can't explain this. I can just suppose the environnement maybe is different and maybe the isAdmin field is present and it was set to true by default ... (but I'm pretty sure I'm wrong on this point) or maybe this line `const userCount = Users.find().count();` is not working properly ...

**Comment by soohwa** [comment]
Anyone feels free to review in order to find this bug ...

**Comment by nztqa** [comment]
My execution log.
"isAdmin" is not inserted.

1. fromAdmin": "true"
```
$ curl -H "Authorization: Bearer xl4zhal8HhMyktnlaQ9E7fTISTFduFb2uem1KZ9pAsm" \
  -H "Content-type:application/json" \
  -X POST \
  http://localhost:3000/api/users \
  -d '{ "username": "tester", "password": "tester", "email": "tester@example.com", "fromAdmin": "true" }'

{
  "_id": "AT6MfLgJ3QrP4DM8n"
}
```
result
```
{
    "_id": "AT6MfLgJ3QrP4DM8n",
    "createdAt": ISODate("2017-10-05T11:29:38.513Z"),
    "services": {
        "password": {
            "bcrypt": "$2a$10$jjNR4MuK7hw1a9l9gesdvOLjHwAspoSxcPO6WDaJi2y2DhUabPmmO"
        }
    },
    "username": "tester",
    "emails": [
        {
            "address": "tester@example.com",
            "verified": false
        }
    ],
    "fromAdmin": true,
    "profile": {}
}
```


2. fromAdmin": "false"
```
$ curl -H "Authorization: Bearer xl4zhal8HhMyktnlaQ9E7fTISTFduFb2uem1KZ9pAsm"
  -H "Content-type:application/json"
  -X POST \
  http://localhost:300/api/users -d '{ "username": "tester1", "password": "tester1", "email": "tester1@example.com", "fromAdmin": "false" }'

{
  "_id": "CiP6gx5F3sBASK4JA"
}
```
result
```
{
    "_id": "CiP6gx5F3sBASK4JA",
    "createdAt": ISODate("2017-10-05T11:30:41.688Z"),
    "services": {
        "password": {
            "bcrypt": "$2a$10$6ZwguctvWqo0TP31gSiad.P73ADiJdK2AykPGSG/sjBo0aysdlOo2"
        }
    },
    "username": "tester1",
    "emails": [
        {
            "address": "tester1@example.com",
            "verified": false
        }
    ],
    "fromAdmin": true,
    "profile": {}
}
```

**Comment by soohwa** [comment]
@nztqa You're right: the only purpose of `fromAdmin` is to avoid "disableRegistration == true", not to grant admin rights like `isAdmin`. And yes, it does not need to be save. Thanks for your patch, i will include it soon.

**Comment by nztqa** [comment]
isAdmin field = Administrator
fromAdmin field = avoid "disableRegistration == true"

Because the name is confusing, it is the source of misunderstanding.
So it's better to change to an appropriate namea nd  add the issue url and comments.

**Pull request merged**
