### PR TITLE
meteor update all packages

### PR DESCRIPTION
**Pull request by brylie**
Related issue #788 

Upgrade Meteor to 1.4.x branch

Upgrade Atmosphere packages

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/957)

### CODE REVIEW

**Comment by xet7** [comment]
@brylie

What commands you used to build this with meteor 1.4 ?

**Comment by stephenmoloney** [comment]
I'm taking a look at this now too...

**Comment by brylie** [comment]
I haven't build the app. I just run `meteor` to start the app. What is the normal 'build' process?

**Comment by stephenmoloney** [comment]
I'd recommend that for testing the build works, to try
```
echo 'NODE_VERSION=v7.8.0' >> .env && echo 'METEOR_RELEASE=1.4.3.2' >> .env && echo 'NPM_VERSION=4.4.4' >> .env && echo 'ARCHITECTURE=linux-x64' >> .env && echo 'SRC_PATH=./' >> .env && sudo docker-compose up -d --build --force-recreate --remove-orphans
```

**Comment by stephenmoloney** [comment]
We'll have to bump meteor 1.4.3.2 --> to 1.4.4 soon too

**Comment by stephenmoloney** [comment]
Right now I'm getting an error 
```
Failed at the bson@0.2.21 install script '(node-gyp rebuild 2> builderror.log) || (exit 0)'. npm ERR! Make sure you have the latest version of node.js and npm installed
If you do, this is most likely a problem with the bson package,
npm ERR! not with npm itself.
```

npm is latest. nodejs is latest --- so some issue with bson there.

**Comment by rhelsing** [comment]
@brylie would you mind updating the meteor version in the Dockerfile as well? @stephenmoloney does anything else need to be changed in the dockerfile?

**Comment by stephenmoloney** [comment]
@rhelsing 
I think it's better not to update the `Dockerfile` until the build is proven to work on a specific meteor version.  I suspect that meteor version 1.4.3.2 is going to be a broken build and is it at the moment.

All this does is add more issues to the `Dockerfile` making it harder to ascertain the issue. 

The ARG variables are deliberately added to the `Dockerfile` to easily override. 

#### example:

```shell
echo 'NODE_VERSION=v7.8.0' >> .env && \ 
echo 'METEOR_RELEASE=1.4.3.2' >> .env && \
echo 'NPM_VERSION=4.4.4' >> .env && \
echo 'ARCHITECTURE=linux-x64' >> .env && \
echo 'SRC_PATH=./' >> .env && \
sudo docker-compose up -d --build --force-recreate
```

Let's change the Dockerfile in the public canonical repo only once we have a proven working build.

**Comment by stephenmoloney** [comment]
@rhelsing @brylie 
Do you know much about package management - i don't use meteor. 

How can I stop npm doing an upgrade of a package automatically?
for example in packages i set npm-mongo to  1.4.45 .
But it keeps getting upgraded automatically by npm.

```
Changes to your project's package version selections:
npm-mongo* upgraded from 1.4.45 to 2.2.24
```

I never asked for the upgrade though - any ideas how to block the upgrade?

**Comment by brylie** [comment]
@stephenmoloney, you can pin an NPM package to a specific version. Something like

```
npm install package@version --save
```

**Comment by stephenmoloney** [comment]
I'm trying to downgrade `npm-mongo` to an older version but I can't that is specified in the `.meteor/versions` file. Seems it forces the upgrade and gives some reason.
@xet7 
Due to using an old version of mongodb, we cannot upgrade mongo version?
Or can we upgrade the mongodb being used?

**Comment by brylie** [comment]
> can we upgrade the mongodb being used?

You can upgrade the running MongoDB instance. [These instructions](https://docs.mongodb.com/manual/tutorial/change-standalone-wiredtiger/) might be helpful.

**Comment by stephenmoloney** [comment]
@brylie I think some issues arose that were more than meets the eye, @xet7 knows more about.
This is why mongodb is fixed in the dockerfile.

**Comment by xet7** [comment]
@stephenmoloney 

Backup your MongoDB 3.2.x and try upgrading to newer version:
https://github.com/wekan/wekan/wiki/Export-Docker-Mongo-Data

I presume newer Meteor 1.4 supports newest MongoDB 3.4.x.

But after upgrade, if uploading images to Wekan crashes Wekan, you need to to go back to newest MongoDB 3.2.x.

I have not had time to try Meteor 1.4. stuff yet.

**Comment by stephenmoloney** [comment]
I may have fixed the dockerbuild -- need to check a few things first

I think you can merge this pull request. I'll make another one later.

**Comment by HLFH** [comment]
@xet7 Hi. What will be the recommended Node.js version now?

**Comment by xet7** [comment]
@HLFH 

Newest 4.x I think.

**Comment by xet7** [comment]
I have moved devel back to Meteor 1.3.

Meteor 1.4 work continues in meteor-1.4 branch.

**Pull request merged**
