### PR TITLE
Comment permissions

### PR DESCRIPTION
**Pull request by rhelsing**
see issue #870 .. probably needs a bit of refactoring, but it accomplishes the intended goal. Let me know what to do next. @xet7

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/925)

### CODE REVIEW

**Comment by xet7** [comment]
@rhelsing 

When testing this, I get errors:
```
   at Document.addMember (packages/mquandalle:collection-mutations/mutations.js:8:20)
    at [object Object].inviteUserToBoard (models/users.js:379:13)
    at packages/check/match.js:107:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check/match.js:106:1)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1708:18)
    at packages/ddp-server/livedata_server.js:711:19
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:709:40
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at packages/ddp-server/livedata_server.js:707:46
    at tryCallTwo (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:45:5)
    at doResolve (/home/user/repos/wekan/.build/bundle/programs/server/npm/node_modules/meteor/promise/node_modules/promise/lib/core.js:200:13)
Sanitized and reported to the client as: Is comment only is required [400]
```

**Comment by rhelsing** [comment]
@xet7 Is this after running `npm test`? all tests pass locally for me and on travis.. what did you do to get this error?

**Comment by xet7** [comment]
@rhelsing 

At runtime, when using Wekan. I will try again, I don't know is this related to Comment permission or some other code.

**Comment by xet7** [comment]
@rhelsing 

How this works? Where do I set comment permissions for user? Can you add screenshots?

**Comment by rhelsing** [comment]
@xet7 regarding this https://github.com/wekan/wekan/pull/925#issuecomment-289122415, I have just submitted a PR to fix: #952

**Pull request merged**
