### PR TITLE
[Resumit] Add disableCardRestoring & disableCardDeleting to allow only board ad…

### PR DESCRIPTION
**Pull request by thuanpq**
…min to restore or remove archived cards

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1343)

### CODE REVIEW

**Comment by xet7** [comment]
@thuanpq 

Disable Card Deleting: As normal user, there is still delete link visible on card and arhived card, it should be hidden.

Disable Card Restoring: As normal user, there is still restore link visible on arhived card, it should be hidden.

When Disable Card Deleting is selected, I get this error to node.js console:

```
Exception while invoking method '/cards/remove' TypeError: Cannot read property 'isBoardAdmin' of undefined
    at Cards.allow.remove (models/cards.js:91:115)
    at packages/allow-deny/allow-deny.js:396:13
    at Array.every (native)
    at [object Object].CollectionPrototype._validatedRemove (packages/allow-deny/allow-deny.js:395:37)
    at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

When Disable Card Restoring is selected, I get this error to node.js console:

```
Exception while invoking method '/cards/remove' TypeError: Cannot read property 'isBoardAdmin' of undefined
    at Cards.allow.remove (models/cards.js:91:115)
    at packages/allow-deny/allow-deny.js:396:13
    at Array.every (native)
    at [object Object].CollectionPrototype._validatedRemove (packages/allow-deny/allow-deny.js:395:37)
    at [object Object].m.(anonymous function) (packages/allow-deny/allow-deny.js:173:46)
    at packages/check.js:130:16
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at Object.exports.Match._failIfArgumentsAreNotAllChecked (packages/check.js:129:41)
    at maybeAuditArgumentChecks (packages/ddp-server/livedata_server.js:1734:18)
    at packages/ddp-server/livedata_server.js:719:19
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:717:40
    at [object Object]._.extend.withValue (packages/meteor.js:1122:17)
    at packages/ddp-server/livedata_server.js:715:46
    at [object Object]._.extend.protocol_handlers.method (packages/ddp-server/livedata_server.js:689:23)
    at packages/ddp-server/livedata_server.js:559:43
```

Control Panel => Settings => General: It's not descriptive enough text. That page should be called Self-Registration.

Control Panel => Setting => Accounts: This shoud be: Permissions. Also move there those Disable Card Deleting and Disable Card Restoring.

**Comment by thuanpq** [comment]
ok I see, will submit another PR later

**Comment by xet7** [comment]
@thuanpq 

You can also try to add your changes to this PR, because there is no merge conflicts currently like in previous PR.

**Comment by xet7** [comment]
@thuanpq

Actually new PR is better, because I have already made many changes and added new release tag etc. Thanks !

**Comment by xet7** [comment]
@thuanpq 

You don't need to change this menu option name:
Control Panel => Settings => Registration

Thanks :)

**Comment by thuanpq** [comment]
@xet7 is ok but looks weird =.=

**Comment by xet7** [comment]
@thuanpq 

Ok, then Self-Registration would be better I think.

**Pull request closed without merging**
