### PR TITLE
Add more dates

### PR DESCRIPTION
**Pull request by rjevnikar**
Add received and end dates - may be useful in future for a gantt view
This is my first PR, please let me know how/what I can improve or fix.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1545)

### CODE REVIEW

**Comment by xet7** [comment]
@rjevnikar 

Please remove other commits, only leave one last commit. Here is info how to remove commits:
https://github.com/wekan/wekan/pull/1470

After that I can test it more.

Thanks!

**Comment by rjevnikar** [comment]
@xet7 - I hope I've squashed the commits all into one now...

**Comment by xet7** [comment]
@rjevnikar 

- Remove all other translations, add new ones only to i18n/en.i18n.json

- Remove changing case of strings at client/components/settings/informationBody.jade

**Comment by xet7** [comment]
@rjevnikar 

Please remove old release tag v0.53

**Comment by xet7** [comment]
Here is how to remove old tag https://gist.github.com/mobilemind/7883996

Remove all text case changes from i18n/en.i18n.json that you also made at
client/components/settings/informationBody.jade .

It would be best that you restore original en.18n.json from latest Wekan commit, and add your changes to there, so original casing and order is preserved.

**Comment by xet7** [comment]
This does not work with rebuild-wekan-meteor-1.6.sh script option 3. I recommend you rename your own fork of wekan, create new fork of wekan, add your changes to those files and i18n/en.i18n.json file, check that it builds and works, and submit new clean pull request. Thanks!

**Pull request closed without merging**
