### PR TITLE
Global Search Function

### PR DESCRIPTION
**Pull request by GSWemigo**
Is there any global search function , like in trello implemented?

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/625)

### CODE REVIEW

**Comment by GSWemigo** [comment]
WHY my request got closed?

**Comment by AlexanderS** [comment]
This should be an issue not a pull request.

**Comment by GSWemigo** [comment]
If there is no search function thats its not an issue

**Comment by AlexanderS** [comment]
The issue is, that there is no search function. **Pull Request** means, that you have an own branch with the required changes to fix a problem and want to get it merged in the upstream (see [Using pull requests](https://help.github.com/articles/using-pull-requests/)), it is not something like a Feature Request. You have opened a Pull Request requesting to merge *devel* into *meteor-1.3*, but *devel* does not fix your problem.

**Pull request closed without merging**
