### PR TITLE
Board-As-Card / Card-As-Card

### LINKED ISSUE #492: Board of boards
Is it possible to have a board of boards?  I would like to use it to track projects and thought that if I could have a board that contains lists like not started started testing and complete and withing each list I could have a card that linked to a project (another board).

### PR DESCRIPTION
**Pull request by andresmanelli**
This PR hopefully implements the import feature of a board or a card (from another board) to an existing board.

It aims to fix #492 and maybe #709 and #1068.

What is implemented:

- Two way data binding for:
  - Checklists: from original card, or own checklists if imported board
  - Description: from original card/board
  - Member assignment: for card _and_ board
  - Comments
  - Activities
  - Attachments
  - Dates / spentTime

What is missing:
  - ~Add link to imported card / board to open that card / board~
  - Bugfixes when necessary :D

### Screenshot
seleccion_002

@xet7 Please try this and let me know if I can add anything else.

---
This change is [Reviewable](https://reviewable.io/reviews/wekan/wekan/1592)

### CODE REVIEW

**Comment by xet7** [comment]
@andresmanelli 

## Linked card or board location

There should be visible somewhere, that where original card is, for example names of [project](https://github.com/wekan/wekan/issues/641#issuecomment-357759642) => board => list. Something logical like that.

**Comment by xet7** [comment]
@andresmanelli 

Please change everywhere in code, model names, translations, database, etc:
* Import => Link
* importedCard => linkedCard
* importedBoard => linkedBoard
* importedId => linkedId

**Comment by andresmanelli** [comment]
@xet7 Rebased and lint-free.

Please let me know what else may I modify.

**Comment by xet7** [comment]
@andresmanelli 

In Link popup:
* Rename topic "Link Card" => "Link"
* Rename right button "Link" => "Link Board"
* Rename bottom button "Link" => "Link Card"
* Also change these everywhere in code, variable names, translations, etc, so it's clear which functionality is used in each case

**Comment by xet7** [comment]
@andresmanelli 

In Wekan lists:
* Rename `+ Add Card` => `+ Add Card or Link`

In Search popup:
* Change title `Search Card` to `Search Card. Click card to add link.`

**Comment by andresmanelli** [comment]
Should the << icons on top of the card >> be visible when the `cardDetails` are closed? You don't explicitly say that. I'm not sure if they should be **added** to `cardDetails` or **removed** from `minicard` if cardDetails are closed.

See :
bitmap


The linked boards are implemented yes:
1. The dates (due, received, etc) were added to the board's model and are actually board values, not linked-board values.
2. The checklists belong to the linked-board card, so they are not referenced by the board itself: If you link the same board in two other boards, each linked-board card will have its own checklists
3. The members are actually added to the board, not the linked-board card.
4. The description is the board's description, and can be edited within the linked-board card details
5. Attachments belong also to that linked-board card only, so same as (2)
6. Activity is the board's activity feed

**Comment by xet7** [comment]
When board is opened, icon should change to opened folder icon.

When card is opened, it should change to opened card or be rotated little to clockwise.

Board and card icons with path at right side of icon should be visible both on card and opened card details at top. Below those is actual card title.

On linked boards, when board card is opened, lists should be visible as checklist names. Checkbox should be added to left side of list name, and also added to lists model, so each list is actually also checklist. Those list checkboxes should be also visible at board's lists, left side of list names, and be able to be checkmarked there.

Checkboxes should be added to board model, left side of board names, and linked-board-cards, where checkbox on board-card can be checkmarked both on card itself and card details.

Checkboxes should be added to card model, left side of card names, and linked-cards, where checkbox on cards and linked-cards can be checkmarked both on card itself and card details. Current static checkmarked icon on cards then will be working as it can be checked and unchecked.

This way it will be: Board checkbox / List checkbox / Card checkbox / Checklists checkbox / ChecklistItem checkbox.

On linked-board-card, there should be count of checkmarked lists, like there is already on linked-card/card count of checkmarked checklists.

On linked-board-card details, between list checkbox and list name, should be count of checked checklists.

Between checklist name checkboxes and checklist checkboxes should be count of checklist items.

**Comment by xet7** [comment]
On linked-board-card attachments, there should be all attachments of linked-board. Each attachment should have path visible above attachment, like `Listname > Cardname`

**Comment by xet7** [comment]
On linked-board-card, there should be buttons `Collapse All` and `Uncollapse All`. That setting should be board-wide, like Hide system messages slider, so if someone is looking at collapsed mode, others are collapsed too on next opened card. If setting is not saved yet, default should be `Collapse All`.

At left side of Listname checkbox should be black triangle https://fontawesome.com/icons/caret-right?style=solid pointing to right. When that triangle is clicked, it should animate clockwise 45 degrees, and reveal all Card names below it. When Card name triangle is clicked, it should expand all Checklist names below it. When checklist name triangle is clicked, it should expand all ChecklistItems below it.



When opened

**Comment by xet7** [comment]
On linked-board-card / lists / card, there should be:
```
> [_] Cardname [external-link-alt-icon]
```
https://fontawesome.com/icons/external-link-alt?style=solid

When external-link-alt-icon is clicked, it opens linked card in new popup.

**Comment by xet7** [comment]
On linked-board-card, there should be these add buttons:
```
+ Add List
  + Add Card
    + Add Checklist
      + Add Checklist Item
```
Those Add texts should be same as previously used ones in card.

When those are collapsed, only `Add List` should be visible below of all of those `> [_] Checklistname`s. When some single checklistname is opened from triangle, it shows other Add possibilities as needed.

**Comment by xet7** [comment]
linked-board-card backround color should be the same as it is in All boards view, originally set as board color.

**Comment by xet7** [comment]
When clicking Search, it looks like that it loads and goes through all cards in the board. This can take a long time, if there is board where is a lot of cards.

Change Search so that it only loads board names to dropdown, and only after in Search field the word to search is written and Enter key pressed from keyboard, it starts searching. Because otherwise everyone just opening Search take resources, even if they were just looking at what is in the menus, and not starting to search something.

**Comment by xet7** [comment]
I think I listed too many requirements.

I'll look does this pull request work in Wekan as it currently is.

**Comment by andresmanelli** [comment]
Sorry for my absence, I will have time to start working on this in a couple of days maybe.

Maybe I can add some more before merge. No promises about timing though.

**Comment by vrms** [comment]
@andresmanelli Super happy and grateful you took this thing on! I'm convinced it's a killer feature which nobody else to my knowledge has thus far. Sorry that apart from suggesting this (among other I believe) I can't help much because I can not code whatsoever.

**Comment by andresmanelli** [comment]
Hello, I've been quite busy. I rebases my branch today. I tested (briefly) locally and it seems to work on top of devel branch.

I will not have time right now to add the requirements noted by @xet7 , so I can propose:

- Add the requirements later as improvements to this feature
- Ask someone from the community to continue my work and add the missing requirements

@xet7 could you retest if this works for you?

@vrms  thanks!

**Comment by xet7** [comment]
@andresmanelli 

Yes I will test. Thanks!

**Comment by xet7** [comment]
@andresmanelli 

Do you have any idea why these Link and Search do not open popup at Sandstorm? Did you disable some code on Sandstorm, using isSandstorm checks?
```
<a class="js-link is-active" href="#">Link</a>
<a class="js-search is-active" href="#">Search</a>
```

**Comment by xet7** [comment]
Doh, using `eslint --fix` did break those Link and Search. Without eslint fixed code works. I'll try to fix.

**Comment by xet7** [comment]
It seems that this does not work on Welcome Board, and newly created Sandstorm board. I'll check is there missing migrations.

**Comment by andresmanelli** [comment]
Welcome Board works for me when I register e new user (locally).

just in case: In order the search to work, you must hit enter. Great to see this merged!

**Comment by lichtamberg** [comment]
This feature doesn't work for me (independent if swimlanes or lists, also when I create a new board), it's just not doing anything after submitting. 



screencast 2018-08-16 11-07-56

**Pull request merged**
